Repository fecgov/fec-cms, pull requests merged in 2018-03, with the labels that each got.

#1819 [MERGE WITH GIT FLOW] fix broken IE an PCE links on committee summary pages
  fec/data/constants.py
  fec/data/templates/macros/tables.jinja
Labels: plz-review

#1817 Applies most recent styles to cards components on data landing page
  fec/data/templates/landing.jinja
Labels: plz-review

#1818 Move Form 5 quarterly reports to 'Regularly filed reports'
  fec/fec/static/js/pages/committee-single.js
Labels: plz-review

#1826 Fixes for RFAI filings
  fec/fec/static/js/pages/candidate-single.js
  fec/fec/static/js/pages/committee-single.js
Labels: plz-review

#1823 update moment package
  package-lock.json
  package.json
Labels: plz-review

#1835 This change makes RFAI inclusive for all request types
  fec/fec/static/js/pages/candidate-single.js
  fec/fec/static/js/pages/committee-single.js
Labels: plz-review

#1844 fixes image path for no headshot image
  fec/home/templates/partials/commissioner.html
  fec/home/templates/partials/current-commissioners.html
Labels: plz-review

#1850 [MERGE WITH GIT FLOW] Change `strip_zero_pad` to only remove leading 0's
  fec/data/templatetags/filters.py
Labels: HOTFIX

#1830 Fix Party Coordinated Expenditure year filters
  fec/data/constants.py
  fec/data/templates/macros/tables.jinja
  fec/data/templates/partials/party-coordinated-expenditures-filter.jinja
Labels: plz-review

#1842 Corrects style on feed pagination component
  fec/fec/static/scss/components/_pagination.scss
Labels: plz-review

#1860 [MERGE WITH GIT FLOW] Add `mur_respondents` filter to "next" and "previous" buttons
  fec/legal/templates/partials/legal-pagination.jinja
Labels: HOTFIX, plz-review

#1837 updated a11y-dialog dependency to fix IE dialog submit issue
  package-lock.json
  package.json
Labels: plz-review

#1872 Update manifest files - inheritance and host attributes have been depreciated
  manifest_base.yml
  manifest_dev.yml
  manifest_feature.yml
  manifest_prod.yml
  manifest_stage.yml
Labels: plz-review

#1881 Fix broken committee link in candidate profile page.
  fec/data/templates/partials/candidate/financial-summary.jinja
Labels: plz-review

#1889 Add primary alternating bg card styles
  fec/fec/static/img/i-calendar--secondary-contrast.svg
  fec/fec/static/img/i-document--secondary-contrast.svg
  fec/fec/static/img/i-elections--primary-contrast.svg
  fec/fec/static/img/i-table--primary-contrast.svg
  fec/fec/static/scss/components/_cards.scss
Labels: plz-review
