Repository fecgov/fec-cms, pull requests merged in 2018-09, with the labels that each got.

#2310 Feature/candidate filings tab new
  fec/data/templates/candidates-single.jinja
  fec/data/templates/partials/candidate/about-candidate.jinja
  fec/data/templates/partials/candidate/filings-tab.jinja
  fec/fec/static/js/pages/candidate-single.js
Labels: plz-review

#2292 Upgrade react and dependencies to v16.4.2
  .eslintrc
  fec/data/templates/layouts/main.jinja
  fec/fec/static/js/draftail/Anchor.js
  fec/fec/static/js/draftail/Glossary.js
  fec/fec/static/js/draftail/SansSerif.js
  fec/fec/static/js/polyfills.js
  fec/fec/tests/js/draftail/anchor.js
  fec/fec/tests/js/draftail/glossary.js
  fec/fec/tests/js/draftail/sansserif.js
  fec/fec/tests/js/draftail/setup.js
  fec/fec/wagtail_hooks.py
  fec/legal/templates/legal-search-results-advisory_opinions.jinja
  fec/webpack.config.js
  karma.conf.js
  package-lock.json
  package.json
Labels: plz-review

#2345 Fix/audit search subcats
  fec/fec/static/js/modules/audit-category-sub-category.js
  fec/fec/static/js/modules/audit_tags.js
  fec/fec/static/js/pages/datatable-audit.js
Labels: Before release

#2346 Resource/Custom page template tweaks
  fec/fec/static/scss/components/_type-styles.scss
  fec/home/blocks.py
  fec/home/models.py
Labels: plz-review

#2347 Update wagtail to v2.2.1 and responsive video styling
  fec/fec/static/scss/base.scss
  fec/fec/static/scss/components/_responsive-object.scss
  requirements.txt
Labels: plz-review

#2364 Make filter macros for office sought, party, and district
  fec/data/templates/macros/filters/districts.jinja
  fec/data/templates/macros/filters/misc.jinja
  fec/data/templates/macros/filters/office-sought.jinja
  fec/data/templates/macros/filters/parties.jinja
  fec/data/templates/macros/filters/support-oppose.jinja
  fec/data/templates/partials/candidates-filter.jinja
  fec/data/templates/partials/candidates-office-filter.jinja
  fec/data/templates/partials/committees-filter.jinja
  fec/data/templates/partials/communication-costs-filter.jinja
  fec/data/templates/partials/filings-filter.jinja
  fec/data/templates/partials/filters/office-sought.jinja
  fec/data/templates/partials/filters/parties.jinja
  fec/data/templates/partials/independent-expenditures-filter.jinja
Labels: plz-review

#2373 Updated links to point to new cms training page
  fec/fec/templates/partials/navigation/nav-help.html
  fec/home/templates/home/candidate-and-committee-services/services_landing_page.html
Labels: plz-review

#2376 Removes hardcoded contact page information
  fec/home/models.py
  fec/home/templates/home/press_landing_page.html
Labels: plz-review

#2384 Fix filings tab responsive issues
  fec/fec/static/js/pages/candidate-single.js
Labels: Before release, plz-review

#2399 Make related media optional in reporting_example template
  fec/home/models.py
Labels: Before release, plz-review

#2365 Reimplement raising and spending bar charts
  fec/data/templates/landing.jinja
  fec/data/templates/macros/bythenumbers.jinja
  fec/data/templates/partials/advanced/raising.jinja
  fec/data/templates/partials/advanced/spending.jinja
  fec/data/templates/raising-bythenumbers.jinja
  fec/data/templates/spending-bythenumbers.jinja
  fec/data/urls.py
  fec/data/views.py
  fec/fec/static/js/pages/bythenumbers.js
Labels: plz-review

#2367 Feedback drawer RECAPTCHA implementation
  .eslintrc
  fec/data/templates/layouts/main.jinja
  fec/data/templates/macros/reaction-box.jinja
  fec/data/views.py
  fec/fec/settings/base.py
  fec/fec/static/js/data-init.js
  fec/fec/static/js/init.js
  fec/fec/static/js/modules/feedback.js
  fec/fec/static/js/modules/reaction-box.js
  fec/fec/static/js/pages/data-advanced.js
  fec/fec/static/js/pages/data-landing.js
  fec/fec/static/js/templates/feedback.hbs
  fec/fec/templates/base.html
  fec/fec/tests/js/feedback.js
Labels: plz-review

#2410 Fix Form 1 and Form 2 original/amendment labels
  fec/fec/static/js/modules/helpers.js
Labels: plz-review
