Repository fecgov/fec-cms, pull requests merged in 2018-11, with the labels that each got.

#2487 Update terms.json to add disclosure date
  fec/fec/static/js/data/terms.json
Labels: plz-review

#2488 show null data in datatables by default
  fec/fec/static/js/modules/tables.js
  fec/fec/tests/js/tables.js
Labels: plz-review

#2495 Implement data table descriptions
  fec/data/templates/partials/advanced/filings-reports.jinja
  fec/data/templates/partials/advanced/loans-debts.jinja
  fec/data/templates/partials/advanced/raising.jinja
  fec/data/templates/partials/advanced/spending.jinja
Labels: plz-review

#2491 Sort nulls last in data tables
  fec/fec/static/js/modules/tables.js
  fec/fec/tests/js/tables.js
Labels: Before release, plz-review

#2500 Fix candidate page 404 errors due to missing district
  fec/data/templates/candidates-single.jinja
  fec/data/templates/partials/candidate/about-candidate.jinja
  fec/data/templatetags/filters.py
  fec/data/views.py
Labels: plz-review

#2505 [MERGE WITH GIT FLOW] Fix candidate filing pages for missing amendment chain
  fec/fec/static/js/modules/helpers.js
Labels: HOTFIX

#2507 Remove setTimout function-elections map
  fec/fec/static/js/modules/election-map.js
Labels: Before release, plz-review

#2510 Remove reaction box feedback from site
  fec/data/templates/landing.jinja
  fec/data/templates/partials/advanced/raising.jinja
  fec/data/templates/partials/advanced/spending.jinja
Labels: Before release, plz-review

#2509 Add imagenumber column to the committee filing tables
  fec/data/templates/macros/entity-pages.jinja
  fec/fec/static/js/pages/committee-single.js
Labels: plz-review

#2511 Turns off sort_nulls_last for receipts, disbursements, and individiua…
  fec/fec/static/js/pages/datatable-disbursements.js
  fec/fec/static/js/pages/datatable-individual-contributions.js
  fec/fec/static/js/pages/datatable-receipts.js
Labels: Before release, plz-review

#2501 Correct Raising text-datatable descriptions
  fec/data/templates/partials/advanced/raising.jinja
Labels: plz-review

#2523 Refer to SERS for archived hearing pages and files
  fec/home/templates/home/commission_meetings.html
Labels: plz-review

#2516 Show robots.txt in all environments except production
  fec/fec/settings/base.py
  fec/fec/settings/dev.py
  fec/fec/settings/production.py
  fec/fec/tests/test_robots.py
  fec/fec/urls.py
Labels: plz-review

#2519 Upgrade django-storages to 1.7.1
  fec/fec/settings/base.py
  requirements.txt
Labels: plz-review

#2518 Upgrade requests to 2.20.1
  requirements.txt
Labels: plz-review

#2513 Add data.json file for data.gov
  fec/fec/templates/data.json
  fec/fec/tests/test_static_files.py
  fec/fec/urls.py
Labels: Before release, plz-review

#2547 Enable sort on employer and occupation columns
  fec/fec/static/js/pages/committee-single.js
Labels: plz-review

#2551 Removed cycle greater than 2006 limitation on candidate and committee…
  fec/data/templates/macros/tables.jinja
Labels: plz-review
