Repository fecgov/fec-cms, pull requests merged in 2018-06, with the labels that each got.

#2029 Feature/restore reverted audit search
  fec/data/constants.py
  fec/data/templates/macros/filters/dropdown-json.jinja
  fec/data/templates/macros/filters/years.jinja
  fec/data/templates/macros/page-header.jinja
  fec/data/templates/partials/audit-filter.jinja
  fec/data/templates/partials/filters/audit-committee-types.jinja
  fec/data/urls.py
  fec/data/views_datatables.py
  fec/fec/static/js/modules/audit-category-sub-category.js
  fec/fec/static/js/modules/audit_tags.js
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/modules/tables.js
  fec/fec/static/js/modules/typeahead.js
  fec/fec/static/js/pages/datatable-audit.js
  fec/fec/static/js/templates/audit_tags.hbs
  fec/fec/static/scss/components/_datatables.scss
  fec/fec/static/scss/components/_filters.scss
  fec/fec/static/scss/components/_list-styles.scss
  fec/fec/static/scss/components/_tags.scss
  fec/fec/static/scss/datatables.scss
Labels: plz-review

#2043 Update terms.json - June
  fec/fec/static/js/data/terms.json
Labels: plz-review

#2035 Fix "Explore all compliance resources" link on menu
  fec/fec/templates/partials/navigation/nav-help.html
Labels: plz-review

#2042 Occupation/Employer filter help-text for All Receipts and Indiv. Contributions
  fec/data/templates/partials/filters/occupation-employer.jinja
  fec/data/templates/partials/individual-contributions-filter.jinja
  fec/data/templates/partials/receipts-filter.jinja
Labels: plz-review

#2060 Closing issue using keyword "resolves" in PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: plz-review

#2045 Include missing "Suite" in committee addresses
  fec/data/views.py
Labels: plz-review

#1979 Update ecosystem guide links on README
  README.md
Labels: plz-review

#2063 updated feedback drawer to new styles based on design ticket
  fec/fec/static/js/templates/feedback.hbs
  fec/fec/static/scss/components/_buttons.scss
  fec/fec/static/scss/components/_feedback.scss
  fec/fec/static/scss/mixins/_utilities.scss
Labels: plz-review

#2076 Fix earmarked contributor name display on Receipts
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/templates/receipts.hbs
Labels: Before release, High priority, Urgent, plz-review

#2086 [MERGE BEFORE RELEASE] Add Govdelivery token to settings/base.py and latest_updates.html
  fec/fec/settings/base.py
  fec/home/templates/home/latest_updates.html
Labels: Before release, plz-review

#2094 Rename calendar category 21 to 'Mid-year and year-end', move to bottom
  fec/fec/constants.py
Labels: plz-review

#2106 Fixed data description link for Contributions by individuals
  fec/data/templates/partials/advanced/bulk-data.jinja
Labels: plz-review

#2110 Audit search "Filter added" popup message for ALL filters
  fec/data/templates/partials/filters/audit-committee-types.jinja
Labels: plz-review

#2116 Contact page url and route maintenance
  fec/data/templates/macros/missing.jinja
  fec/fec/static/js/templates/feedback.hbs
  fec/fec/static/js/templates/tables/noData.hbs
  fec/fec/templates/partials/footer-navigation.html
  fec/fec/templates/partials/navigation/nav-about.html
  fec/fec/urls.py
  fec/home/templates/home/collection_page.html
  fec/home/templates/home/custom_page.html
  fec/home/templates/home/resource_page.html
  fec/home/tests/test_views.py
  fec/home/views.py
Labels: plz-review

#2102 Add next 4 election years (2019-2022) to candidates data table
  fec/data/templates/macros/filters/years.jinja
  fec/data/templates/partials/candidates-filter.jinja
Labels: plz-review

#2114 Replace banner with new image
  fec/fec/static/img/hero-home.jpg
Labels: plz-review

#1984 Election profile page design
  fec/data/templates/elections.jinja
  fec/data/templates/macros/cycle-select.jinja
  fec/data/templates/macros/reporting-info.jinja
  fec/data/templates/partials/elections/about-this-election-tab.jinja
  fec/data/templates/partials/elections/election-data-and-compliance-tab.jinja
  fec/data/templates/partials/elections/election-profile-cards.jinja
  fec/data/templates/partials/elections/sidebar-nav.jinja
  fec/data/views.py
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/pages/elections.js
  fec/fec/static/js/templates/comparison.hbs
  fec/fec/static/js/templates/electionDates.hbs
  fec/fec/static/js/templates/electionOffices.hbs
  fec/fec/static/scss/components/_cards.scss
  fec/fec/static/scss/components/_icon-headings.scss
  fec/fec/static/scss/elections.scss
Labels: plz-review

#2123 Text for presidential state election offices
  fec/data/templates/partials/elections/about-this-election-tab.jinja
Labels: Before release, plz-review

#2133 Allow characters in MUR names
  fec/legal/urls.py
Labels: Before release, plz-review

#2140 padding for document dwnld links
  fec/fec/static/scss/components/_datatables.scss
Labels: plz-review

#2143 Restore lost icons on datatable/calendar pages
  fec/fec/static/scss/calendar.scss
  fec/fec/static/scss/datatables.scss
Labels: Before release, plz-review
