Repository fecgov/fec-cms, pull requests merged in 2019-09, with the labels that each got.

#3142 3141 Fix Aggregate Totals numbers
  fec/fec/static/js/widgets/aggregate-totals-box.js
Labels: Please review, Work: Front-end

#3126 Upgrade ESLint, resolve errors
  fec/fec/static/js/modules/accessibility.js
  fec/fec/static/js/modules/analytics.js
  fec/fec/static/js/modules/cycle-select.js
  fec/fec/static/js/modules/election-search.js
  fec/fec/static/js/modules/election-summary.js
  fec/fec/static/js/modules/election-utils.js
  fec/fec/static/js/modules/events.js
  fec/fec/static/js/modules/filings.js
  fec/fec/static/js/modules/filters/date-filter.js
  fec/fec/static/js/modules/filters/validate-date-filters.js
  fec/fec/static/js/modules/fips.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/modules/keyword-modal.js
  fec/fec/static/js/modules/line-chart-committees.js
  fec/fec/static/js/modules/line-chart.js
  fec/fec/static/js/modules/other-spending-totals.js
  fec/fec/static/js/modules/performance.js
  fec/fec/static/js/modules/skip-nav.js
  fec/fec/static/js/modules/toggle.js
  fec/fec/static/js/pages/bythenumbers.js
  fec/fec/static/js/pages/candidate-single.js
  fec/fec/static/js/pages/committee-single.js
  fec/fec/static/js/pages/contact-form.js
  fec/fec/static/js/pages/data-browse-data.js
  fec/fec/static/js/pages/data-landing.js
  fec/fec/static/js/pages/datatable-candidates-office.js
  fec/fec/static/js/pages/datatable-committees.js
  fec/fec/static/js/pages/datatable-disbursements.js
  fec/fec/static/js/pages/datatable-filings.js
  fec/fec/static/js/pages/datatable-operating-expenditures.js
  fec/fec/static/js/pages/datatable-reports.js
  fec/fec/static/js/pages/election-lookup.js
  fec/fec/static/js/pages/elections.js
  fec/fec/static/js/pages/legal.js
  fec/fec/tests/js/date-filter.js
  fec/fec/tests/js/dropdowns.js
  fec/fec/tests/js/election-search.js
  fec/fec/tests/js/line-chart.js
  fec/fec/tests/js/site-nav.js
  fec/fec/tests/js/table-switcher.js
  fec/fec/tests/js/typeahead-filter.js
  package-lock.json
  package.json
Labels: Please review, Security: high, Work: Front-end

#3171 Update the Updates message
  fec/home/templates/home/latest_updates.html
Labels: Please review

#3170 [MERGE WITH GIT FLOW] Fix missing/duplicate authorizing candidates
  fec/data/views.py
Labels: HOTFIX, Please review

#3130 3071 Org chart styles
  fec/fec/static/scss/base.scss
  fec/fec/static/scss/components/_fec-org-chart.scss
Labels: Please review, Work: Front-end

#3177 Update link in the Record search "no results" message
  fec/home/templates/home/latest_updates.html
Labels: Please review

#3180 Change to check settings.FEC_CMS_ENVIRONMENT
  fec/data/templates/layouts/main.jinja
  fec/data/templates/layouts/widgets.jinja
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
Labels: Please review, Work: Front-end

#3174 Feature/2929 contribs by state
  fec/data/templates/layouts/main.jinja
  fec/data/templates/macros/bythenumbers.jinja
  fec/data/templates/macros/widgets.jinja
  fec/data/templates/partials/widgets/contributions-by-state.jinja
  fec/data/templates/raising-bythenumbers.jinja
  fec/data/templates/widgets/contributions-by-state.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/modules/filters/filter-typeahead.js
  fec/fec/static/js/modules/typeahead.js
  fec/fec/static/js/widgets/aggregate-totals.js
  fec/fec/static/js/widgets/contributions-by-state-box.js
  fec/fec/static/js/widgets/contributions-by-state.js
  fec/fec/static/js/widgets/widget-vars.js
  fec/fec/static/scss/widgets/contributions-by-state.scss
  fec/webpack.config.js
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#3187 Fix "Filter this data" buttons for filings
  fec/data/templates/macros/entity-pages.jinja
  fec/data/templates/partials/candidate/filings-tab.jinja
  fec/data/templates/partials/committee/filings.jinja
  fec/data/views.py
  fec/fec/static/js/pages/candidate-single.js
  fec/fec/static/js/pages/committee-single.js
Labels: Before release, Please review

#3162 Add connected organization and organization type for SSFs to the committee about tab
  fec/data/templates/committees-single.jinja
  fec/data/templates/partials/committee/about-committee.jinja
  fec/data/tests/test_committee.py
  fec/data/views.py
Labels: Before release, Please review

#3196 [MERGE WITH GIT FLOW] Hotfix: Increase application memory on prod
  manifest_prod.yml
Labels: HOTFIX

#3207 Update error message to include 'itemized'
  fec/fec/static/js/widgets/contributions-by-state-box.js
Labels: Please review
