Repository fecgov/fec-cms, pull requests merged in 2019-08, with the labels that each got.

#3091 3087 Change Google Analytics Account Numbers from 18F's
  fec/data/templates/layouts/main.jinja
  fec/data/templates/layouts/widgets.jinja
  fec/fec/static/js/modules/analytics.js
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
Labels: Before release, Please review, Work: Front-end

#3092 upgrade to django@1.11.23
  requirements.txt
Labels: Security: moderate

#3095 Fix mailto link in ao, legal and legal search templates
  fec/fec/settings/base.py
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/legal-search-results-advisory_opinions.jinja
  fec/legal/templates/macros/legal.jinja
Labels: Please review

#3084 Add SSF, lobbyist, and leadership PAC filters back to receipts/disbursement datatables
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/macros/filters/spender-committee-types.jinja
  fec/data/templates/partials/disbursements-filter.jinja
  fec/data/templates/partials/individual-contributions-filter.jinja
  fec/data/templates/partials/receipts-filter.jinja
Labels: Please review

#3120 [Merge with openFEC 3919]Fix Candidate profile financial summary page inconsistent data.
  fec/data/api_caller.py
  fec/data/templates/candidates-single.jinja
  fec/data/templates/partials/candidate/financial-summary.jinja
  fec/data/tests/test_candidate.py
  fec/data/views.py
Labels: Please review

#3124 Add security response headers
  fec/fec/middleware.py
  fec/fec/settings/base.py
  package-lock.json
  package.json
Labels: Please review
