Repository fecgov/fec-cms, pull requests merged in 2019-10, with the labels that each got.

#3208 WCCF: Update candidate cycle in link and make election years even
  fec/fec/static/js/polyfills.js
  fec/fec/static/js/widgets/contributions-by-state-box.js
  package.json
Labels: Please review

#3214 feature/3204 WCCF Individual Contributions links
  fec/fec/static/js/widgets/contributions-by-state-box.js
Labels: Please review, Work: Front-end

#3229 Feature/3216 wccf map colors
  fec/data/templates/macros/widgets.jinja
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/widgets/contributions-by-state-box.js
Labels: Please review, Work: Front-end

#3233 Feature/3232 wccf committee api call
  fec/fec/static/js/widgets/contributions-by-state-box.js
Labels: Please review, Work: Front-end

#3190 Apply styles from home
  fec/fec/static/scss/components/_overviews.scss
Labels: Work: Front-end

#3202 Disable pre-1980 election profile page links
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/templates/candidates.hbs
Labels: Please review

#3206 Escape special chars
  fec/fec/static/js/modules/filters/filter-base.js
  fec/fec/static/js/modules/filters/filter-typeahead.js
  fec/fec/static/js/modules/filters/text-filter.js
  fec/fec/static/js/modules/filters/typeahead-filter.js
Labels: Please review

#3234 Fix candidate profile no financial activity issue
  fec/data/tests/test_candidate.py
  fec/data/views.py
Labels: Please review

#3255 Update 500 error message
  fec/fec/templates/500.html
Labels: Please review

#3256 add condition for amendment_chain != null
  fec/fec/static/js/modules/helpers.js
Labels: Bug, Please review

#3264 Fix committee info and raising/spending tabs for future candidates
  fec/data/api_caller.py
  fec/data/tests/test_candidate.py
  fec/data/views.py
Labels: Please review

#3250 Raise the dropdown z-index
  fec/fec/static/js/draftail/components/Modal.js
  fec/fec/static/js/legal/filters/CitationFilter.js
  fec/fec/static/scss/_variables.scss
  fec/fec/static/scss/components/_dropdowns.scss
  fec/fec/static/scss/components/_search-bar.scss
  fec/fec/static/scss/widgets/contributions-by-state.scss
Labels: Please review, Work: Front-end

#3260 feature/2943 Update styles for dropdowns' perfect-scrollbar components
  fec/fec/static/scss/components/_dropdowns.scss
Labels: Please review, Work: Front-end

#3265 Feature/3246 wccf in ie
  fec/data/templates/partials/widgets/contributions-by-state.jinja
  fec/data/templates/widgets/contributions-by-state.jinja
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/widgets/contributions-by-state-box.js
  fec/fec/static/scss/widgets/contributions-by-state.scss
  tasks.py
Labels: Please review, Work: Front-end

#3273 Add fec.gov domain to allowed image sources in CSP
  fec/fec/middleware.py
Labels: Please review

#3277 Feature/1635 social images update
  fec/data/templates/partials/meta-tags.jinja
  fec/data/templatetags/filters.py
  fec/data/views.py
  fec/data/views_datatables.py
  fec/fec/static/img/social/fec-data.png
  fec/fec/static/img/social/fec-help.png
  fec/fec/static/img/social/fec-legal.png
  fec/fec/static/img/social/fec-logo.png
  fec/fec/static/img/social/fec-microphone.png
  fec/fec/static/img/social/fec-microphones.png
  fec/fec/static/img/social/fec-pen.png
  fec/fec/static/img/social/fec-seal.png
  fec/fec/static/img/social/general.png
  fec/fec/templates/partials/meta-tags.html
  fec/fec/templates/partials/update.html
  fec/home/models.py
  fec/home/templatetags/filters.py
  fec/home/views.py
  fec/legal/views.py
Labels: Please review, Work: Front-end

#3278 Updates for global site search
  fec/fec/constants.py
  fec/search/management/commands/index_pages.py
  fec/search/management/data/transition_pages.json
  fec/search/management/data/web_app_pages.json
  fec/search/management/instructions.md
Labels: Please review

#3297 Remove CSP reporting from production
  fec/fec/middleware.py
Labels: Before release, Please review

#3300 Switch to better-supported typeahead package
  fec/fec/static/js/modules/typeahead.js
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#3288 Feature/pre-election tables, stripe rows by state
  fec/fec/static/js/modules/filters/filter-typeahead.js
  fec/fec/static/js/modules/filters/typeahead-filter.js
  fec/fec/static/js/pages/reporting-dates-tables.js
  fec/fec/static/scss/components/_table-styles.scss
Labels: Please review
