Repository fecgov/fec-cms, pull requests merged in 2019-07, with the labels that each got.

#3008 Fix URL path in links for candidate raw filings links
  fec/fec/static/js/modules/columns.js
Labels: Please review

#3003 2792, 2821, 2901 Security issues
  fec/webpack.config.js
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#2957 Address polyfills for Internet Explorer (IE)
  fec/data/templates/landing.jinja
  fec/data/templates/layouts/main.jinja
  fec/data/templates/layouts/widgets.jinja
  fec/data/templates/partials/meta-tags.jinja
  fec/data/templates/partials/warnings.jinja
  fec/data/templates/raising-bythenumbers.jinja
  fec/data/templates/spending-bythenumbers.jinja
  fec/fec/settings/dev.py
  fec/fec/static/js/object-assign-polyfill.js
  fec/fec/static/js/polyfills.js
  fec/fec/static/js/widgets/aggregate-totals-box.js
  fec/fec/static/scss/widgets/aggregate-totals.scss
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/meta-tags.html
  fec/home/templates/home/calendar.html
  fec/home/templates/home/candidate-and-committee-services/guides.html
  fec/home/templates/home/home_page.html
  fec/webpack.config.js
  package-lock.json
  package.json
  tasks.py
Labels: Please review, Work: Front-end

#3010 2965 Adjust right padding for select elements
  fec/fec/static/scss/elements/_forms.scss
Labels: Please review, Work: Front-end

#3014 Fix radio button selected-state
  fec/fec/static/scss/elements/_forms.scss
Labels: Please review

#3036 Add MUR date filter
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/legal-search-results-adrs.jinja
  fec/legal/templates/legal-search-results-afs.jinja
  fec/legal/templates/legal-search-results-murs.jinja
  fec/legal/templates/partials/legal-pagination.jinja
  fec/legal/templates/partials/legal-search-results-mur.jinja
  fec/legal/views.py
Labels: Please review

#3026 Specify public (client-side) and private (server-side) keys
  README.md
  fec/data/api_caller.py
  fec/data/templates/layouts/main.jinja
  fec/data/templates/layouts/widgets.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/legal/LegalSearch.js
  fec/fec/static/js/legal/filters/CitationFilter.js
  fec/fec/static/js/modules/calendar-helpers.js
  fec/fec/static/js/modules/filters/filter-typeahead.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/modules/typeahead.js
  fec/fec/static/js/pages/contact-form.js
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/tests/js/setup.js
  fec/search/views.py
  tasks.py
Labels: Please review

#3030 Fix click-through links from candidate profiles to receipts/disbursements
  fec/data/templates/macros/tables.jinja
  fec/data/templates/partials/candidate/financial-summary.jinja
  fec/data/views.py
Labels: Please review

#3048 Remove Line 24, disbursements, edit spending tab language
  fec/data/constants.py
  fec/data/templates/partials/browse-data/spending.jinja
Labels: Please review

#3053 Update guides.html
  fec/home/templates/home/candidate-and-committee-services/guides.html
Labels: Please review

#3012 Specify 2-year totals explicitly
  fec/data/templates/partials/committee/spending.jinja
  fec/fec/static/js/pages/candidate-single.js
  fec/fec/static/js/pages/committee-single.js
Labels: Before release, Please review

#3042 3021 Upgrade the patch (also latest) version of lodash
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#3062 Apply reset filter to receipts and individual contributions datatable
  fec/fec/static/js/modules/filters/filter-set.js
  fec/fec/static/js/modules/filters/filter-tags.js
  fec/fec/static/js/modules/tables.js
Labels: Please review

#3075 bug-Candidate profile page inconsistent financial data( from candidate list page)
  fec/fec/static/js/modules/columns.js
Labels: Please review

#3052 Update aggregate totals links with full election cycles
  fec/data/templates/elections.jinja
  fec/data/views.py
  fec/fec/static/js/modules/column-helpers.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/tests/js/column-helpers.js
Labels: Please review
