Repository fecgov/fec-cms, pull requests merged in 2019-06, with the labels that each got.

#2925 Feature/2700 fec monospace currency font
  fec/data/templates/macros/tables.jinja
  fec/fec/static/fonts/fec-currencymono-bold.eot
  fec/fec/static/fonts/fec-currencymono-bold.ttf
  fec/fec/static/fonts/fec-currencymono-bold.woff
  fec/fec/static/fonts/fec-currencymono-bold.woff2
  fec/fec/static/fonts/fec-currencymono-bolditalic.eot
  fec/fec/static/fonts/fec-currencymono-bolditalic.ttf
  fec/fec/static/fonts/fec-currencymono-bolditalic.woff
  fec/fec/static/fonts/fec-currencymono-bolditalic.woff2
  fec/fec/static/fonts/fec-currencymono-italic.eot
  fec/fec/static/fonts/fec-currencymono-italic.ttf
  fec/fec/static/fonts/fec-currencymono-italic.woff
  fec/fec/static/fonts/fec-currencymono-italic.woff2
  fec/fec/static/fonts/fec-currencymono-regular.eot
  fec/fec/static/fonts/fec-currencymono-regular.ttf
  fec/fec/static/fonts/fec-currencymono-regular.woff
  fec/fec/static/fonts/fec-currencymono-regular.woff2
  fec/fec/static/fonts/fec-mono-regular.eot
  fec/fec/static/fonts/fec-mono-regular.otf
  fec/fec/static/fonts/fec-mono-regular.ttf
  fec/fec/static/fonts/fec-mono-regular.woff
  fec/fec/static/fonts/fec-mono-regular.woff2
  fec/fec/static/js/modules/column-helpers.js
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/modules/table-columns.js
  fec/fec/static/js/pages/candidate-single.js
  fec/fec/static/js/pages/committee-single.js
  fec/fec/static/js/templates/top-entity-row.hbs
  fec/fec/static/scss/_fonts.scss
  fec/fec/static/scss/_variables.scss
  fec/fec/static/scss/components/_type-styles.scss
  fec/fec/static/scss/widgets/aggregate-totals.scss
  fec/fec/tests/js/tables.js
  fec/webpack.config.js
  package.json
Labels: Please review, Work: Front-end

#2933 Fix H/S/P candidate datatable breadcrumb capitalization
  fec/data/views_datatables.py
  fec/fec/static/js/pages/datatable-candidates-office.js
Labels: Before release, Please review

#2930 Update missing processed data message
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/object-assign-polyfill.js
  fec/fec/static/js/pages/committee-single.js
  fec/fec/static/js/templates/tables/noData.hbs
Labels: Before release, Please review

#2934 Remove extra line in candiate datatables
  fec/data/templates/partials/candidates-office-filter.jinja
Labels: Before release, Please review

#2938 2889 Update 'No Results' message for Updates
  fec/home/templates/home/latest_updates.html
Labels: Please review, Work: Front-end

#2941 Remove SSFs from receipts and individual contributions datatable
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/partials/individual-contributions-filter.jinja
  fec/data/templates/partials/receipts-filter.jinja
Labels: Please review

#2940 updated Report time period filter tooltip
  fec/data/templates/macros/filters/date.jinja
  fec/data/templates/macros/filters/years.jinja
Labels: Before release, Please review

#2954 2951 Remove monospace font from column heads (2)
  fec/fec/static/js/modules/columns.js
  fec/fec/static/scss/components/_type-styles.scss
Labels: Please review, Work: Front-end

#2955 "Filter this data" button link to regularly scheduled reports
  fec/data/templates/partials/candidate/other-spending-tab.jinja
  fec/data/templates/partials/committee/spending.jinja
  fec/fec/static/js/modules/filters/filter-set.js
  fec/fec/static/js/modules/filters/filter-typeahead.js
Labels: Bug, Please review

#2960 [MERGE WITH GIT FLOW] 2959 column headers font
  fec/fec/static/scss/components/_type-styles.scss
Labels: Please review, Work: Front-end

#2968 Fix mismatched case/vertical spacing on Cand. profile pages
  fec/fec/static/js/templates/electionCycles.hbs
Labels: Please review

#2926 Add checkbox to exclude incumbents that are not seeking re-election
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/templates/partials/candidates-filter.jinja
  fec/data/templates/partials/candidates-office-filter.jinja
  fec/data/templates/partials/filters/active-candidates.jinja
Labels: Please review

#2963 Feature/2948-2956/filter-this-data-button
  fec/data/templates/partials/candidate/other-spending-tab.jinja
  fec/data/templates/partials/committee/spending.jinja
  fec/fec/static/js/modules/filters/filter-set.js
  fec/fec/static/js/modules/filters/filter-typeahead.js
Labels: Bug, Please review

#2982 Remove extra space causing bad link
  fec/data/templates/partials/committee/raising.jinja
Labels: Before release

#2977 Adjust z-index of .data-table
  fec/fec/static/scss/components/_datatables.scss
Labels: Please review

#2979 Temporarily Remove SSF/Leadership PACS options from Disbursements datatable
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/macros/filters/spender-committee-types.jinja
  fec/data/templates/partials/disbursements-filter.jinja
  fec/data/templates/partials/individual-contributions-filter.jinja
  fec/data/templates/partials/receipts-filter.jinja
Labels: Before release, Please review

#2975 Add raw filings section to candidate profile page
  fec/data/templates/candidates-single.jinja
  fec/data/templates/macros/entity-pages.jinja
  fec/data/templates/partials/candidate/filings-tab.jinja
  fec/data/utils.py
  fec/data/views.py
  fec/fec/static/js/modules/filters/filter-set.js
  fec/fec/static/js/modules/filters/filter-typeahead.js
  fec/fec/static/js/pages/candidate-single.js
Labels: Please review

#2992 Fix 404 bug for House candidate profile page
  fec/data/views.py
Labels: Please review

#3002 Feature/2988 remove clear all filters
  fec/fec/static/js/modules/filters/filter-tags.js
  fec/fec/static/js/modules/tables.js
Labels: Please review, Work: Front-end

#2947 Add analytics
  fec/fec/static/js/widgets/aggregate-totals-box.js
Labels: Please review
