Repository fecgov/fec-cms, pull requests merged in 2019-12, with the labels that each got.

#3299 Fix committee summary page with wrong form or cmte_type.
  fec/data/api_caller.py
  fec/data/templates/committees-single.jinja
  fec/data/templates/partials/committee/about-committee.jinja
  fec/data/templates/partials/committee/filings.jinja
  fec/data/templates/partials/committee/financial-summary.jinja
  fec/data/templates/partials/committee/raising.jinja
  fec/data/templates/partials/committee/spending.jinja
  fec/data/tests/test_committee.py
  fec/data/views.py
  fec/fec/static/js/pages/committee-single.js
Labels: Please review

#3407 Fixed typo on communication costs section
  fec/data/templates/partials/candidate/other-spending-tab.jinja
Labels: Please review

#3380 Datatables handle >10 committee_ids
  fec/fec/static/js/modules/tables.js
  fec/fec/tests/js/tables.js
Labels: Please review

#3427 Remove 'None' value from list cycles_has_activity in ofec_committee_h…
  fec/data/tests/test_committee.py
  fec/data/views.py
Labels: Please review

#3409 Add error message close button for downloads
  fec/fec/static/js/modules/download.js
  fec/fec/static/scss/components/_downloads.scss
Labels: Please review, Work: Front-end

#3430 Modify format of archived MURs with one document
  fec/legal/templates/legal-archived-mur.jinja
Labels: Before release, Please review
