Repository fecgov/fec-cms, pull requests merged in 2019-04, with the labels that each got.

#2773 Change page-relative links to site-relative
  fec/data/templates/partials/browse-data/bulk-data.jinja
  fec/data/templates/partials/browse-data/candidates.jinja
Labels: Work: Front-end, plz-review

#2775 Update Django
  requirements.txt
Labels: Work: Front-end, plz-review

#2766 FEC-CMS : Add snyk vulnerability links
  README.md
Labels: plz-review

#2768 Feature/2744 aggregate totals box
  fec/data/templates/macros/aggregate-totals.jinja
  fec/data/templates/macros/bythenumbers.jinja
  fec/fec/static/js/modules/aggregate-totals.js
  fec/fec/static/scss/components/_aggregate-totals-block.scss
  fec/webpack.config.js
Labels: Work: Front-end, plz-review

#2804 Fix custom table block rendering
  fec/fec/static/scss/components/_table-styles.scss
  fec/home/blocks.py
Labels: plz-review

#2818 Make breadcrumbs render proper color based on parent section
  fec/fec/templates/partials/breadcrumbs.html
  fec/home/models.py
  fec/home/templates/home/resource_page.html
  tasks.py
Labels: plz-review

#2809 Feature/2744 aggregate totals module
  fec/fec/static/fonts/fec-mono-regular.eot
  fec/fec/static/fonts/fec-mono-regular.otf
  fec/fec/static/fonts/fec-mono-regular.ttf
  fec/fec/static/fonts/fec-mono-regular.woff
  fec/fec/static/fonts/fec-mono-regular.woff2
  fec/fec/static/js/modules/aggregate-totals.js
  fec/fec/static/scss/modules/aggregate-totals.scss
  fec/gulpfile.js
  fec/webpack.config.js
  package-lock.json
  package.json
Labels: Work: Front-end, plz-review

#2834 Add download only API key to CMS
  fec/data/templates/layouts/main.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/modules/tables.js
Labels: Before release, plz-review

#2847 Consistent menu bar indicator
  fec/data/views.py
  fec/fec/templates/partials/breadcrumbs.html
  fec/fec/templates/partials/navigation/navigation.html
  fec/home/models.py
  fec/home/views.py
Labels: plz-review

#2854 [MERGE BEFORE RELEASE] Raising-Spending barcharts - disable non-pres election years for Safari-and-IPhone
  fec/fec/static/js/modules/top-entities.js
Labels: Before release, plz-review

#2850 [depends on openFEC PR3714]Change field name to 'loan_source_name' for loans filter
  fec/data/templates/partials/loans-filter.jinja
Labels: plz-review
