Repository fecgov/fec-cms, pull requests merged in 2020-01, with the labels that each got.

#3439 Update guides.html
  fec/home/templates/home/candidate-and-committee-services/guides.html
Labels: Please review

#3437 Update terms.json to add terms
  fec/fec/static/js/data/terms.json
Labels: Please review

#3298 Add most recent Form 1 to committee profile pages
  fec/data/api_caller.py
  fec/data/templates/partials/candidate/about-candidate.jinja
  fec/data/templates/partials/committee/about-committee.jinja
  fec/data/tests/test_candidate.py
  fec/data/tests/test_committee.py
  fec/data/views.py
Labels: Please review

#3446 fix name text for raw efile
  fec/data/templates/partials/receipts-filter.jinja
Labels: Bug, PI board, Please review

#3452 Update statute landings page
  fec/legal/templates/legal-statutes-landing.jinja
Labels: Please review

#3453 Full-width page legal citations + add-ons
  fec/fec/static/js/pages/reporting-dates-tables.js
  fec/fec/static/scss/components/_table-styles.scss
  fec/home/migrations/0108_fullwidthpage_citations.py
  fec/home/models.py
  fec/home/templates/home/full_width_page.html
  tasks.py
Labels: Please review

#3457 Trigger resize when toggling content
  fec/fec/static/js/modules/toggle.js
Labels: Please review, Work: Front-end

#3438 Independent expenditures datatable: add current version filter and version status
  fec/data/templates/macros/filters/checkbox.jinja
  fec/data/templates/macros/filters/districts.jinja
  fec/data/templates/macros/filters/office-sought.jinja
  fec/data/templates/macros/filters/parties.jinja
  fec/data/templates/macros/filters/states.jinja
  fec/data/templates/macros/filters/version-status.jinja
  fec/data/templates/partials/datatable-modal.jinja
  fec/data/templates/partials/elections/election-data-and-compliance-tab.jinja
  fec/data/templates/partials/filings-filter.jinja
  fec/data/templates/partials/filters/form-type.jinja
  fec/data/templates/partials/filters/version-status.jinja
  fec/data/templates/partials/independent-expenditures-filter.jinja
  fec/data/templates/partials/reports-filter.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/data-init.js
  fec/fec/static/js/modules/filters/filter-panel.js
  fec/fec/static/js/pages/datatable-independent-expenditures.js
  fec/fec/static/js/templates/independent-expenditures.hbs
Labels: Please review

#3474 Upgrade Django from 1.11.23 to 1.11.27
  requirements.txt
Labels: Please review, Work: Front-end

#3475 Remove reaction box from WCCF feature
  fec/data/templates/raising-bythenumbers.jinja
  fec/fec/settings/base.py
Labels: Please review

#3487 [Merging to release branch] Display presidential map data for 2020 (Deploy on 1/29)
  fec/data/api_caller.py
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/views.py
Labels: Before release, High priority, Please review

#3499 [HOTFIX - MERGE-WITH-GITFLOW] Link to e-filing form
  fec/data/templates/partials/browse-data/filings-reports.jinja
Labels: HOTFIX, Please review
