Repository fecgov/fec-cms, pull requests merged in 2020-03, with the labels that each got.

#3594 [fec-cms] Enable circleci pipeline
  .circleci/config.yml
  requirements.txt
Labels: Please review

#3586 Add new homepage icon links and banner
  fec/fec/static/img/Homepage-hero-image-flag.jpg
  fec/fec/static/img/i-complex--legal--gray-lightest.svg
  fec/fec/static/img/i-complex--regreport--gray-lightest.svg
  fec/fec/static/img/map-chart-icon.svg
  fec/fec/static/scss/components/_hero.scss
  fec/fec/static/scss/layout/_grid.scss
  fec/home/templates/home/home_page.html
Labels: Please review

#3591 Feature/3517 presidential map 3
  fec/data/templates/pres-finance-map.jinja
  fec/data/templates/widgets/pres-finance-map.jinja
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/widgets/pres-finance-map-box.js
  fec/fec/static/scss/components/_buttons.scss
  fec/fec/static/scss/widgets/pres-finance-map.scss
  fec/webpack.config.js
Labels: Work: Front-end

#3621 [before cut release]Change to call /communication_cost/aggregates
  fec/fec/static/js/pages/committee-single.js
Labels: Please review

#3622 new presidential links on browse data/candidates page
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/fec/static/img/map-us-states-primary-contrast.svg
Labels: Please review

#3613 Update Django to 2.2.11
  requirements.txt
Labels: Please review

#3612 Fix acorn vulnerability
  package-lock.json
  package.json
Labels: Please review

#3629 Calculate presidential bulk data coverage dates
  fec/data/api_caller.py
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/tests/test_utils.py
  fec/data/utils.py
  fec/data/views.py
Labels: Before release, Please review

#3627 Feature/3600 presidential map 4
  fec/data/templates/pres-finance-map.jinja
  fec/data/templates/widgets/pres-finance-map.jinja
  fec/fec/static/js/data-init.js
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/widgets/pres-finance-map-box.js
  fec/fec/static/scss/widgets/pres-finance-map.scss
Labels: Please review, Work: Front-end

#3634 [MERGE WITH GIT FLOW] Hotfix/fix coverage dates
  fec/data/tests/test_utils.py
  fec/data/utils.py
Labels: HOTFIX, Please review

#3636 fix aligment in IE of candidate column on pres map
  fec/fec/static/scss/widgets/pres-finance-map.scss
  tasks.py
Labels: Work: Front-end

#3647 [MERGE WITH GIT FLOW][HOTFIX] Add reaction box to presidential map, IE fixes
  fec/data/templates/pres-finance-map.jinja
  fec/fec/static/scss/base.scss
  fec/fec/static/scss/widgets/pres-finance-map.scss
Labels: HOTFIX, Please review
