Repository fecgov/fec-cms, pull requests merged in 2020-06, with the labels that each got.

#3799 add package lock file for jquery upgrade
  package-lock.json
Labels: Please review

#3723 feature/3688 admin fine calc
  fec/fec/static/js/modules/calc-admin-fines-logic.js
  fec/fec/static/js/modules/calc-admin-fines-modal.js
  fec/fec/static/js/modules/calc-admin-fines.js
  fec/fec/static/scss/base.scss
  fec/fec/static/scss/components/_calc-admin-fines.scss
  fec/fec/templates/base.html
  fec/fec/tests/js/calc-admin-fines.js
  fec/webpack.config.js
  karma.conf.js
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#3809 Change stylesheet class name to is-active-status and is_terminated_status
  fec/data/templates/committees-single.jinja
  fec/fec/static/scss/components/_datatables.scss
Labels: Please review

#3780 Add additional limits to fields in Receipts, Individual contributions, and Disbursements datatable
  fec/data/templates/macros/filters/typeahead-filter.jinja
  fec/data/templates/partials/disbursements-filter.jinja
  fec/data/templates/partials/independent-expenditures-filter.jinja
  fec/data/templates/partials/individual-contributions-filter.jinja
  fec/data/templates/partials/receipts-filter.jinja
  fec/fec/static/js/modules/tables.js
  fec/fec/tests/js/tables.js
Labels: Before release, Please review

#3795 Update search.gov index for deleted/added transition pages
  fec/search/management/data/transition_pages.json
Labels: Please review

#3812 Add tv ad-example styles to SCSS
  fec/fec/static/scss/components/_responsive-object.scss
Labels: Please review

#3831 Add active/terminated indictor on dropdown list.
  fec/fec/static/js/modules/typeahead.js
  fec/fec/static/scss/base.scss
  fec/fec/static/scss/calendar.scss
  fec/fec/static/scss/data-landing.scss
Labels: Please review

#3828 Replaced financial document icon with new example icon
  fec/fec/static/img/example-circle.svg
  fec/fec/static/scss/_icon-variables.scss
  fec/fec/static/scss/components/_icon-headings.scss
  fec/home/templates/blocks/reporting-example-cards.html
  fec/home/templates/home/collection_page.html
Labels: Please review, Work: Front-end

#3813 Gracefully fail when there are no MUR docs
  fec/data/api_caller.py
  fec/legal/templates/legal-archived-mur.jinja
  fec/legal/templates/legal-current-mur.jinja
Labels: Please review

#3814 Handle mid-cycle candidates who have transferred committees
  fec/data/templates/macros/missing-transferred.jinja
  fec/data/templates/partials/candidate/financial-summary.jinja
  fec/data/templates/partials/committee/financial-summary.jinja
  fec/data/views.py
Labels: Before release, Please review

#3852 fix flake8 formatting errors
  fec/data/views.py
Labels: Please review

#3863 Remove reaction box code from pres map
  fec/data/templates/pres-finance-map.jinja
Labels: Please review

#3851 Update downloads error message
  fec/fec/static/js/modules/download.js
Labels: Please review

#3857 Search.gov env var update
  fec/fec/settings/base.py
Labels: Please review
