Repository fecgov/fec-cms, pull requests merged in 2020-09, with the labels that each got.

#4019 [Before release] Add one PCC -> PAC conversion
  fec/data/views.py
Labels: Before release, Please review, Work: CMS back-end

#4018 Update campaign finance statistics pages
  fec/data/templates/browse-data.jinja
  fec/data/templates/partials/browse-data/historical.jinja
  fec/fec/templates/partials/navigation/nav-data.html
Labels: Please review, Work: Front-end

#4035 Add empty string when null action
  fec/data/api_caller.py
  fec/data/tests/test_legal_search.py
Labels: Before release, Bug, Work: Front-end, Work: UX/Design

#4034 disable two year period on candidate page when cycles is null
  fec/fec/static/js/modules/cycle-select.js
  fec/fec/tests/js/cycle-select.js
Labels: Before release, Please review

#4041 Add one PCC -> PAC conversion
  fec/data/views.py
Labels: Before release, Please review, Work: CMS back-end

#4048 [Before release] Add one converted committee manually
  fec/data/views.py
Labels: Before release, Work: CMS back-end

#4049 Update .gov banner with revised text
  fec/fec/templates/partials/usa-banner.html
Labels: Please review

#4066 Pin greenlet@0.4.16 to fix build problem
  requirements.txt
Labels: Bug

#4042 [MERGE WITH GIT FLOW] Release/public 20200922
  fec/data/api_caller.py
  fec/data/templates/browse-data.jinja
  fec/data/templates/partials/browse-data/historical.jinja
  fec/data/tests/test_legal_search.py
  fec/data/views.py
  fec/fec/static/js/modules/cycle-select.js
  fec/fec/templates/partials/navigation/nav-data.html
  fec/fec/tests/js/cycle-select.js
  requirements.txt
Labels: Please review

#4072 update xhr of communication-costs to communication_costs
  fec/fec/static/js/pages/datatable-communication-costs.js
Labels: Please review

#4059 Update sitemap_pdf.xml
  fec/search/management/data/sitemap_pdf.xml
Labels: Please review

#4076 4027 Upgrade Django from 2.2.13 to 2.2.16
  requirements.txt
Labels: Please review, Work: Front-end

#4085 Include self in connect-src
  fec/fec/middleware.py
Labels: High priority, Please review, Work: Front-end
