Repository fecgov/fec-cms, pull requests merged in 2020-04, with the labels that each got.

#3639 update python to v3.7
  .circleci/config.yml
  README.md
  package.json
  requirements.txt
  runtime.txt
Labels: Please review

#3607 Policy and guidance search in CMS
  fec/fec/settings/base.py
  fec/fec/templates/partials/breadcrumbs.html
  fec/fec/urls.py
  fec/home/templates/home/feed_base.html
  fec/search/templates/search/policy_guidance_search_page.html
  fec/search/views.py
Labels: Please review

#3663 Add best bets count to total count
  fec/search/templates/search/policy_guidance_search_page.html
  fec/search/views.py
Labels: Please review

#3614 add sitemaps for mvp
  fec/search/management/data/sitemap_html.xml
  fec/search/management/data/sitemap_pdf.xml
Labels: Guidance Page

#3669 fix guidance search on load
  fec/search/views.py
Labels: Before release, Please review

#3664 [MERGE WITH GIT FLOW] Release/public 20200414
  .circleci/config.yml
  README.md
  fec/fec/settings/base.py
  fec/fec/static/js/widgets/pres-finance-map-box.js
  fec/fec/templates/partials/breadcrumbs.html
  fec/fec/urls.py
  fec/home/templates/home/feed_base.html
  fec/search/templates/search/policy_guidance_search_page.html
  fec/search/views.py
  package.json
  requirements.txt
  runtime.txt
  tasks.py
Labels: Please review

#3696 Update sitemap for html guidance pages
  fec/search/management/data/sitemap_html.xml
Labels: Please review

#3695 Update sitemap-pdf for changes to files
  fec/search/management/data/sitemap_pdf.xml
Labels: Please review

#3697 Add changes from `release/public 20200414` back to `develop`
  .circleci/config.yml
  README.md
  fec/fec/settings/base.py
  fec/fec/static/js/widgets/pres-finance-map-box.js
  fec/fec/templates/partials/breadcrumbs.html
  fec/fec/urls.py
  fec/home/templates/home/feed_base.html
  fec/search/templates/search/policy_guidance_search_page.html
  fec/search/views.py
  package.json
  requirements.txt
  runtime.txt
  tasks.py
Labels: Please review

#3702 Changes to Guidance search
  fec/fec/settings/base.py
  fec/fec/templates/partials/navigation/nav-legal.html
  fec/fec/urls.py
  fec/home/templates/home/candidate-and-committee-services/services_landing_page.html
  fec/search/templates/search/policy_guidance_search_page.html
Labels: Before release, Please review

#3707 Bold "https://" in banner
  fec/fec/templates/partials/usa-banner.html
Labels: Please review

#3700 USA and env-specific banners
  fec/data/templates/layouts/main.jinja
  fec/fec/settings/base.py
  fec/fec/static/img/angle-arrow-down-primary.png
  fec/fec/static/img/angle-arrow-down-primary.svg
  fec/fec/static/img/angle-arrow-up-primary.png
  fec/fec/static/img/angle-arrow-up-primary.svg
  fec/fec/static/img/icon-dot-gov.svg
  fec/fec/static/img/icon-https.svg
  fec/fec/static/scss/components/_site-header.scss
  fec/fec/static/scss/elections.scss
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/env-banner.html
  fec/fec/templates/partials/usa-banner.html
Labels: Before release

#3701 Filter to create valid anchors out of numeric titles
  fec/home/templates/blocks/section.html
  fec/home/templates/partials/section-nav.html
  fec/home/templatetags/filters.py
Labels: Before release, Please review

#3710 [HOTFIX] [MERGE WITH GIT FLOW] Fix download export link
  fec/fec/static/js/widgets/pres-finance-map-box.js
Labels: HOTFIX, Please review

#3714 Update wagtail to 2.7.2 (security update)
  requirements.txt
Labels: Please review
