Repository fecgov/fec-cms, pull requests merged in 2020-08, with the labels that each got.

#3966 Feature/3803 admin fines 2020
  fec/fec/static/js/modules/calc-admin-fines-logic.js
  fec/fec/tests/js/calc-admin-fines.js
Labels: Please review, Work: Front-end

#3970 Fix RTE mobile image resize , example-img, and table-spacing bugs.
  fec/fec/static/scss/components/_articles.scss
  fec/fec/static/scss/components/_examples.scss
  fec/fec/static/scss/components/_richtext.scss
Labels: Please review

#3987 [HOTFIX - MERGE WITH GITFLOW] Add recaptcha and additional logging to RAD contact form
  fec/home/templates/home/contact-form.html
  fec/home/views.py
Labels: HOTFIX, High priority

#3991 SNYK - 3983 Update lodash
  package-lock.json
  package.json
Labels: Please review, Security: high, Work: Front-end

#3996 Update feedback box language
  fec/fec/static/js/templates/feedback.hbs
Labels: Work: Front-end

#3999 [MERGE WITH GIT FLOW] [HOTFIX] Add more candidates to manual conversion list
  fec/data/views.py
Labels: HOTFIX, Please review, Work: CMS back-end, Work: Content

#4002 Add one PCC->PAC converted committee
  fec/data/views.py
Labels: Before release, Please review, Work: CMS back-end

#3990 Update wagtail to address pillow vulnerability
  requirements.txt
Labels: Before release, Please review, Security: moderate, Work: Front-end

#3995 Add external page link to "Read next" sidebar on ResourcePage
  fec/home/models.py
  fec/home/templates/home/resource_page.html
Labels: Please review
