Repository fecgov/fec-cms, pull requests merged in 2020-07, with the labels that each got.

#3853 Feature/3797 header menu update
  fec/fec/static/scss/_grid.scss
  fec/fec/static/scss/components/_list-styles.scss
  fec/fec/static/scss/components/_mega-menu.scss
  fec/fec/static/scss/components/_nav.scss
  fec/fec/templates/partials/navigation/nav-about.html
  fec/fec/templates/partials/navigation/nav-data.html
  fec/fec/templates/partials/navigation/nav-help.html
  fec/fec/templates/partials/navigation/nav-legal.html
Labels: Before release, Please review, Work: Front-end

#3890 update lodash v4.17.19 to fix the synk vulnerability
  package-lock.json
  package.json
Labels: Please review

#3889 Update wagtail to 2.7.3, exclude static directories from linting
  pytest.ini
  requirements.txt
Labels: Please review

#3904 Fix the sort by candidate and spent by columns on the elections and spending pages.
  fec/fec/static/js/modules/table-columns.js
  fec/fec/static/js/pages/committee-single.js
Labels: Please review

#3922 add ajv to package.json
  package-lock.json
  package.json
Labels: Please review, Security: high

#3933 Handle ServiceNow API outage or URL change
  fec/fec/forms.py
  fec/fec/settings/base.py
  fec/fec/tests/test_form.py
  fec/home/templates/home/contact-form.html
  fec/home/views.py
Labels: Please review, Work: CMS back-end, Work: Front-end, Work: UX/Design
