Repository fecgov/fec-cms, pull requests merged in 2020-02, with the labels that each got.

#3526 Upgrade handlebars
  package-lock.json
  package.json
Labels: Please review, Security: high, Work: Front-end

#3551 Conditionally disable current version and add report type toggle to raw
  fec/data/templates/macros/filters/version-status.jinja
  fec/data/templates/partials/independent-expenditures-filter.jinja
  fec/fec/static/js/modules/tables.js
Labels: Please review

#3552 Update version methodology
  fec/data/templates/macros/filters/version-status.jinja
  fec/data/templates/partials/filings-filter.jinja
  fec/data/templates/partials/independent-expenditures-filter.jinja
  fec/data/templates/partials/reports-filter.jinja
Labels: Please review

#3547 Feature/3514 presidential map 1
  fec/data/templates/pres-finance-map.jinja
  fec/data/templates/widgets/pres-finance-map.jinja
  fec/data/urls.py
  fec/data/views.py
  fec/fec/settings/base.py
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/polyfills.js
  fec/fec/static/js/widgets/pres-finance-map-box.js
  fec/fec/static/scss/widgets/pres-finance-map.scss
  fec/webpack.config.js
Labels: Please review, Work: Front-end

#3561 [MERGE AFTER openFEC 4220] Fix number for transfers in
  fec/data/templates/widgets/pres-finance-map.jinja
Labels: Please review

#3557 Update gunicorn to 19.10.0
  requirements.txt
  tasks.py
Labels: Please review

#3574 Simplify template language
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/task-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Please review

#3563 [Merge after testing ticket] Update wagtail to v2.7 and django to v2.2.10 pkgs
  fec/fec/settings/base.py
  fec/fec/tests/test_robots.py
  fec/fec/urls.py
  fec/home/migrations/0001_initial.py
  fec/home/migrations/0003_auto_20150819_0342.py
  fec/home/migrations/0004_checklistpage.py
  fec/home/migrations/0006_auto_20150819_0546.py
  fec/home/migrations/0009_contactpage.py
  fec/home/migrations/0010_calendarpage.py
  fec/home/migrations/0011_ssfchecklistpage.py
  fec/home/migrations/0012_partychecklistpage.py
  fec/home/migrations/0013_auto_20160427_2133.py
  fec/home/migrations/0014_nonconnectedchecklistpage.py
  fec/home/migrations/0109_auto_20200219_1316.py
  fec/home/models.py
  requirements.txt
Labels: Please review
