Repository fecgov/fec-cms, pull requests merged in 2020-11, with the labels that each got.

#4126 Update requests library to resolve security vulnerability in urllib3
  requirements.txt
Labels: Please review, Security: high

#4148 Implement rolling deployment
  .circleci/config.yml
  README.md
  manifest_dev.yml
  manifest_feature.yml
  manifest_prod.yml
  manifest_stage.yml
  tasks.py
Labels: Please review

#4161 Add internal route to CMS, add network policy to deploy script
  manifest_dev.yml
  manifest_prod.yml
  manifest_stage.yml
  tasks.py
Labels: Please review

#4193 Automate using API for PCC to PAC conversion committees
  fec/data/templates/macros/missing-transferred.jinja
  fec/data/templates/partials/candidate/financial-summary.jinja
  fec/data/tests/test_committee.py
  fec/data/views.py
Labels: Before release, Please review

#4197 Remove public app URLs
  manifest_dev.yml
  manifest_prod.yml
  manifest_stage.yml
Labels: Before release, Please review

#4209 Upgrade datatables.net to v1.10.22
  package-lock.json
  package.json
Labels: Please review

#4195 Feature/4057 sponsor name to committee profile
  fec/data/templates/committees-single.jinja
  fec/data/templates/partials/committee/about-committee.jinja
  fec/data/views.py
Labels: Before release, Please review, Work: Front-end

#4215 Fix typo
  tasks.py
Labels: Before release, Please review

#4211 4154 Add site status link to footer menu
  fec/fec/templates/partials/footer-navigation.html
Labels: Please review, Work: Front-end
