Repository fecgov/fec-cms, pull requests merged in 2020-10, with the labels that each got.

#4091 Feature/4090 csp updates for wagtail
  fec/fec/middleware.py
Labels: Before release, Please review, Work: Front-end

#4086 Consolidate GTM code, update to use environments
  fec/data/templates/layouts/main.jinja
  fec/data/templates/layouts/widgets.jinja
  fec/data/templates/partials/google-tag-manager-noscript.jinja
  fec/data/templates/partials/google-tag-manager-script.jinja
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/google-tag-manager-noscript.html
  fec/fec/templates/partials/google-tag-manager-script.html
Labels: Before release, Please review, Work: Front-end

#4087 Update ua-parser-js@0.7.22
  package-lock.json
  package.json
Labels: Security: high

#4093 update circleci config
  .circleci/config.yml
Labels: Please review

#4103 Regenerate code.json, add config file
  README.md
  code-gov-config.json
  fec/fec/templates/code.json
Labels: Please review

#4088 Summary data tables
  fec/fec/constants.py
  fec/fec/static/js/pages/statistical-summary.js
  fec/fec/static/scss/components/_table-styles.scss
  fec/home/migrations/0110_auto_20200930_2200.py
  fec/home/models.py
  fec/home/templates/home/custom_page.html
  tasks.py
Labels: Before release, Please review

#4141 [HOTFIX - MERGE WITH GITFLOW] Fix homepage event priority
  fec/fec/static/js/modules/home-events.js
Labels: HOTFIX, Please review

#4136 Update cf cli to version 7
  .circleci/config.yml
  README.md
  tasks.py
Labels: Please review, Work: Infrastructure

#4134 [Before release] Change link to new summary tables landing
  fec/data/templates/partials/browse-data/historical.jinja
Labels: Before release, Please review

#4147 Updates link to the policy page
  fec/fec/templates/partials/navigation/nav-legal.html
Labels: Please review

#4145 Updates links to policy and other guidance page
  fec/home/templates/home/legal/legal_resources_landing.html
  fec/search/templates/search/policy_guidance_search_page.html
Labels: Please review

#4153 Feature/4152 upgrade to node 14
  .circleci/config.yml
  package-lock.json
  package.json
Labels: Please review, Work: Front-end
