Repository fecgov/fec-cms, pull requests merged in 2020-12, with the labels that each got.

#4238 Fix candidate profile pages that have no committees
  fec/data/views.py
Labels: Before release, Please review

#4239 Fix committee profile page 404
  fec/data/views.py
Labels: Please review, Work: CMS back-end

#4227 Feature/4220 node package vulnerabilities
  fec/fec/static/js/polyfills.js
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#4249 [MERGE WITH GIT FLOW][HOTFIX] Fix committee 404
  fec/data/views.py
Labels: HOTFIX

#4219 Feature/3313 smallest menu height
  fec/fec/static/scss/components/_nav.scss
  fec/fec/static/scss/components/_site-header.scss
  fec/fec/templates/partials/env-banner.html
Labels: Please review, Work: Front-end

#4233 Add leadership PAC sponsor filter to committees datatable
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/partials/committees-filter.jinja
Labels: Please review

#4250 Feature/headers update
  fec/fec/middleware.py
Labels: Please review, Work: Front-end

#4192 Feature/4104 Remove GTM Conditionals
  fec/data/templates/layouts/main.jinja
  fec/data/templates/layouts/widgets.jinja
  fec/data/templates/partials/google-tag-manager-noscript.jinja
  fec/data/templates/partials/google-tag-manager-script.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/modules/analytics.js
  fec/fec/static/js/modules/election-search.js
  fec/fec/static/js/modules/keyword-modal.js
  fec/fec/static/js/modules/urls.js
  fec/fec/static/js/pages/bythenumbers.js
  fec/fec/static/js/pages/data-landing.js
  fec/fec/static/js/pages/reaction-box.js
  fec/fec/static/js/vendor/tablist.js
  fec/fec/static/js/widgets/aggregate-totals-box.js
  fec/fec/static/js/widgets/contributions-by-state-box.js
  fec/fec/static/js/widgets/pres-finance-map-box.js
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/google-tag-manager-noscript.html
  fec/fec/templates/partials/google-tag-manager-script.html
  fec/fec/tests/js/analytics.js
  fec/fec/tests/js/urls.js
Labels: Before release, Please review, Work: Front-end

#4285 [MERGE WITH GITFLOW - HOTFIX] Do not cache CMS admin
  fec/fec/middleware.py
Labels: HOTFIX

#4272 upgrade datatables.net to v1.10.23
  package-lock.json
  package.json
Labels: Please review
