Repository fecgov/fec-cms, pull requests merged in 2021-12, with the labels that each got.

#4970 [MERGE WITH GITFLOW]Release/public 20211130
  fec/data/constants.py
  fec/fec/static/scss/components/_glossary.scss
  fec/home/templates/home/collection_page.html
  fec/home/templates/home/contact_page.html
  fec/home/templates/home/custom_page.html
  fec/home/templates/home/example_page.html
  fec/home/templates/home/full_width_page.html
  fec/home/templates/home/oig_landing_page.html
  fec/home/templates/home/press_landing_page.html
  fec/legal/templates/legal-admin_fine.jinja
  fec/legal/templates/partials/legal-search-results-afs.jinja
  fec/legal/views.py
Labels: release-branch

#4976 added new oig category and updated names of 2 categories
  fec/fec/constants.py
  fec/home/migrations/0120_auto_20211201_1130.py
Labels: Please review

#4973 Change to modal window for methodology overview
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/browse-data/spending.jinja
  fec/data/templates/partials/widgets/contributions-by-state.jinja
  fec/fec/static/scss/components/_headings.scss
Labels: Please review

#4971 4967 SNYK - json-schema (request)
  package-lock.json
  package.json
Labels: Please review, Work: Front-end, High priority, Security: high

#4974 Add pac, IE, and auth committees filter tooltips
  fec/data/templates/macros/filters/committee-types.jinja
Labels: Please review

#4983 Update sitemap_pdf.xml
  fec/search/management/data/sitemap_pdf.xml
Labels: Please review

#4990 Filter padding on statute and regulations search
  fec/fec/static/scss/components/_buttons.scss
  fec/legal/templates/legal-search-results-regulations.jinja
  fec/legal/templates/legal-search-results-statutes.jinja
Labels: Please review

#4982 Make menu_title optional, restore it show in Wagtail page explorer
  fec/home/migrations/0121_auto_20211206_1255.py
  fec/home/models.py
Labels: Please review
