Repository fecgov/fec-cms, pull requests merged in 2021-01, with the labels that each got.

#4297 [Before release] Update bulk data links for 2022
  fec/data/templates/partials/browse-data/bulk-data.jinja
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/templates/partials/browse-data/committees.jinja
  fec/data/templates/partials/browse-data/filings-reports.jinja
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/browse-data/spending.jinja
Labels: Before release, Please review

#4313 4266 Removing ua-parser-js from package
  package.json
Labels: Please review, Work: Front-end

#4317 Hotfix/2021 admin fines
  fec/fec/static/js/modules/calc-admin-fines-logic.js
  fec/fec/tests/js/calc-admin-fines.js
Labels: HOTFIX, Please review, Work: Front-end

#4311 Feature/4099 oig landing page
  fec/fec/static/icons/input/arrow-target.svg
  fec/fec/static/icons/input/clipboard-checklist.svg
  fec/fec/static/icons/input/decree.svg
  fec/fec/static/icons/input/exclamation-bubble.svg
  fec/fec/static/icons/input/org-chart.svg
  fec/fec/static/icons/input/shield-scales.svg
  fec/fec/static/icons/output/arrow-target.svg
  fec/fec/static/icons/output/clipboard-checklist.svg
  fec/fec/static/icons/output/decree.svg
  fec/fec/static/icons/output/exclamation-bubble.svg
  fec/fec/static/icons/output/org-chart.svg
  fec/fec/static/icons/output/shield-scales.svg
  fec/fec/static/img/hero-oig.png
  fec/fec/static/img/logo-oig-color.svg
  fec/fec/static/scss/_icon-variables.scss
  fec/fec/static/scss/components/_cards.scss
  fec/fec/static/scss/components/_examples.scss
  fec/fec/static/scss/components/_hero.scss
  fec/fec/static/scss/components/_posts.scss
  fec/fec/templates/partials/breadcrumbs.html
  fec/home/blocks.py
  fec/home/migrations/0111_oiglandingpage.py
  fec/home/migrations/0112_auto_20210112_1100.py
  fec/home/models.py
  fec/home/templates/home/oig_landing_page.html
  fec/home/templates/partials/oig-most-recent.html
  fec/home/templatetags/oig_most_recent.py
Labels: Before release, Please review, Work: Front-end

#4327 Add optional `API_KEY_PUBLIC_CALENDAR` setting
  fec/fec/settings/base.py
  fec/fec/static/js/modules/calendar-helpers.js
  fec/fec/templates/base.html
  fec/fec/tests/js/calendar.js
  fec/fec/tests/js/setup.js
Labels: Before release, Please review, Work: CMS back-end

#4320 [MERGE WITH GITFLOW] Release/public 20210119
  fec/fec/settings/base.py
  fec/fec/static/icons/input/arrow-target.svg
  fec/fec/static/icons/input/clipboard-checklist.svg
  fec/fec/static/icons/input/decree.svg
  fec/fec/static/icons/input/exclamation-bubble.svg
  fec/fec/static/icons/input/org-chart.svg
  fec/fec/static/icons/input/shield-scales.svg
  fec/fec/static/icons/output/arrow-target.svg
  fec/fec/static/icons/output/clipboard-checklist.svg
  fec/fec/static/icons/output/decree.svg
  fec/fec/static/icons/output/exclamation-bubble.svg
  fec/fec/static/icons/output/org-chart.svg
  fec/fec/static/icons/output/shield-scales.svg
  fec/fec/static/img/hero-oig.png
  fec/fec/static/img/logo-oig-color.svg
  fec/fec/static/js/modules/calendar-helpers.js
  fec/fec/static/scss/_icon-variables.scss
  fec/fec/static/scss/components/_cards.scss
  fec/fec/static/scss/components/_examples.scss
  fec/fec/static/scss/components/_hero.scss
  fec/fec/static/scss/components/_posts.scss
  fec/fec/templates/base.html
  fec/fec/templates/partials/breadcrumbs.html
  fec/fec/tests/js/calendar.js
  fec/fec/tests/js/setup.js
  fec/home/blocks.py
  fec/home/migrations/0111_oiglandingpage.py
  fec/home/migrations/0112_auto_20210112_1100.py
  fec/home/models.py
  fec/home/templates/home/candidate-and-committee-services/services_landing_page.html
  fec/home/templates/home/oig_landing_page.html
  fec/home/templates/partials/oig-most-recent.html
  fec/home/templatetags/oig_most_recent.py
  package-lock.json
  package.json
Labels: release-branch

#4333 [MERGE WITH GIT FLOW] (Hotfix) Fix upcoming events on home page
  fec/data/templates/layouts/main.jinja
  fec/fec/templates/home_base.html
Labels: HOTFIX, Please review

#4314 Jinja autoescape
  fec/data/jinja2.py
  fec/home/templates/home/meeting_page.html
  fec/home/templates/partials/jobs.html
Labels: Before release, Please review, Security: high

#4337 Display committee section only when cmte_dsgn is of type P, A or J.
  fec/data/templates/candidates-single.jinja
  fec/data/templates/partials/candidate/about-candidate.jinja
Labels: Before release, Please review

#4336 Fix prototype pollution vulnerability
  package-lock.json
  package.json
Labels: Please review
