Repository fecgov/fec-cms, pull requests merged in 2021-03, with the labels that each got.

#4431 Fix syntax and clean code
  fec/data/templates/partials/candidate/about-candidate.jinja
  fec/data/templates/partials/committee/about-committee.jinja
  fec/data/tests/test_candidate.py
Labels: Before release, Please review

#4424 4390 bump lodash from 4.17.20 to 4.17.21
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#4428 Feature/4168 optimization preloads
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/meta-tags-preloads.html
Labels: Please review, Work: Front-end

#4434 Feature/4187 list child nodes
  fec/fec/static/js/data/terms.json
  fec/home/templates/home/home_page.html
  fec/legal/templates/legal-advisory-opinion.jinja
Labels: Before release, Please review, Work: Front-end

#4457 Change Audit Reports to title case in data table only
  fec/fec/static/js/pages/datatable-audit.js
Labels: Before release, Please review

#4449 Feature/4171 o10n preconnect to required origins
  fec/data/templates/layouts/main.jinja
  fec/data/templates/partials/meta-tags-preconnects.jinja
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/meta-tags-preconnects.html
Labels: Before release, Please review, Work: Front-end

#4420 Remove recently migrated transition pages from global search
  fec/search/management/data/transition_pages.json
Labels: Before release, Please review

#4452 Replace 'mark_safe' with 'format_html'
  fec/home/templatetags/filters.py
Labels: Before release, Please review

#4463 Add apostrophe
  fec/fec/templates/home_base.html
Labels: High priority, Please review, Work: Front-end

#4464 Add apostrophe
  fec/fec/templates/home_base.html
Labels: High priority, Please review, Work: Front-end

#4456 ARIA/accessibility fixes for mobile menu and search/typeahead
  fec/data/templates/layouts/main.jinja
  fec/fec/static/js/modules/dropdowns.js
  fec/fec/static/js/modules/filters/filter-typeahead.js
  fec/fec/static/js/modules/site-nav.js
  fec/fec/static/js/modules/typeahead.js
  fec/fec/static/scss/components/_nav.scss
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/navigation/navigation.html
Labels: Before release, Please review

#4474 Update sitemap_pdf-xml
  fec/search/management/data/sitemap_pdf.xml
Labels: Please review

#4498 [Adding to hotfix branch] Fix filter when results have `{` or `}`
  fec/home/templatetags/filters.py
  fec/home/tests/test_filters.py
Labels: Please review

#4466 Exclude hearings from open mtg tab/fix open mtg search
  fec/home/views.py
Labels: Before release, Please review

#4410 JS tests for campaign finance archive
  fec/fec/static/js/modules/statistical-summary-archive.js
  fec/fec/static/js/pages/statistical-summary-archive.js
  fec/fec/tests/js/statistical-summary-archive.js
  karma.conf.js
Labels: Before release, Please review

#4482 Fix committee terminated bug on committee profile page
  fec/data/views.py
  fec/legal/templates/legal-archived-mur.jinja
  fec/legal/templates/legal-current-mur.jinja
Labels: Before release, Please review

#4500 Replace sanitize-html
  fec/fec/static/js/modules/helpers.js
  package-lock.json
  package.json
Labels: Before release, Please review, Work: Front-end

#4507 [MERGE WITH GIT FLOW] Release/public 20210330
  .github/PULL_REQUEST_TEMPLATE.md
  fec/data/views.py
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/modules/statistical-summary-archive.js
  fec/fec/static/js/pages/statistical-summary-archive.js
  fec/fec/tests/js/statistical-summary-archive.js
  fec/home/views.py
  fec/legal/templates/legal-archived-mur.jinja
  fec/legal/templates/legal-current-mur.jinja
  fec/search/management/data/sitemap_pdf.xml
  karma.conf.js
  package-lock.json
  package.json
  requirements.txt
Labels: Please review
