Repository fecgov/fec-cms, pull requests merged in 2021-05, with the labels that each got.

#4574 Convert _.template to ES6
  fec/fec/static/js/modules/column-helpers.js
  fec/fec/static/js/modules/filters/filter-tags.js
  fec/fec/static/js/modules/filters/filter-typeahead.js
  fec/fec/static/js/modules/filters/text-filter.js
  fec/fec/static/js/modules/maps.js
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#4564 Feature/4542 simple document list for custompage
  fec/fec/static/scss/components/_documents.scss
  fec/home/blocks.py
  fec/home/migrations/0114_auto_20210430_1346.py
  fec/home/models.py
  fec/home/templates/blocks/document-list.html
  fec/home/templates/blocks/simple-document-list.html
  fec/home/templatetags/filters.py
Labels: Please review

#4583 4188 Change maximum-scale to 5
  fec/data/templates/partials/meta-tags.jinja
  fec/fec/templates/partials/meta-tags.html
Labels: Before release, Please review, Work: Front-end

#4582 Feature/4175 reduce impact of third party code
  fec/data/templates/layouts/main.jinja
  fec/data/templates/partials/meta-tags-preconnects.jinja
  fec/fec/static/js/modules/feedback.js
  fec/fec/static/js/modules/load-recaptcha.js
  fec/fec/static/js/pages/contact-form.js
  fec/fec/static/js/pages/reaction-box.js
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/meta-tags-preconnects.html
Labels: Before release, Please review, Work: Front-end

#4589 4562 SNYK - Upgrade Wagtail
  requirements.txt
Labels: Please review, Work: Front-end

#4590 4509 SNYK LXML
  requirements.txt
Labels: Please review, Work: Front-end

#4609 Add category to doc page drpdwn/fix ResourcePg filtering
  fec/fec/constants.py
  fec/home/migrations/0115_auto_20210506_2326.py
  fec/home/templatetags/document_feed.py
Labels: Please review

#4612 Feature/4610 fix read-more links
  fec/fec/static/js/init.js
Labels: Before release, Please review

#4633 [HOTFIX - MERGE WITH GITFLOW] Fix election profile page contributor state datatable
  fec/fec/static/js/modules/column-helpers.js
  fec/fec/tests/js/column-helpers.js
Labels: HOTFIX, Please review

#4638 Feature/4637 commissioner photos height
  fec/fec/static/scss/components/_icon-headings.scss
  fec/home/templates/home/alert_for_emergency_use_only.html
  fec/home/templates/home/home_page_banner_announcement.html
  fec/home/templates/partials/commissioner.html
  fec/home/templates/partials/current-commissioners.html
Labels: Please review, Work: Front-end

#4647 Remove redirected transition pages from the global search index
  fec/search/management/data/transition_pages.json
  fec/search/management/instructions.md
Labels: Global Search, Please review
