Repository fecgov/fec-cms, pull requests merged in 2021-04, with the labels that each got.

#4517 Added Administrative termination to the glossary
  fec/fec/static/js/data/terms.json
Labels: Please review

#4508 Upgrade ua-parser-js
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#4519 Fix unable view 2020 filings
  fec/data/tests/test_committee.py
  fec/data/views.py
  fec/fec/static/js/pages/committee-single.js
Labels: Before release, Please review

#4528 add administratively terminated committee status
  fec/data/templates/committees-single.jinja
  fec/data/views.py
Labels: Before release, Please review

#4504 4176 passive listeners
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/widgets/contributions-by-state-box.js
  fec/fec/static/js/widgets/pres-finance-map-box.js
  package-lock.json
  package.json
Labels: Before release, Please review, Work: Front-end

#4518 4384 Wagtail upgrade (plug Django and testing packages)
  fec/extend_admin/wagtailadmin/widgets/chooser.html
  fec/fec/settings/base.py
  fec/fec/static/scss/components/_responsive-object.scss
  fec/fec/static/scss/elements/_elements.scss
  fec/fec/static/scss/elements/_typography.scss
  fec/fec/templates/long_page.html
  fec/fec/templates/partials/body-blocks.html
  fec/fec/wagtail_hooks.py
  fec/fec/wsgi.py
  fec/home/blocks.py
  fec/home/migrations/0002_create_homepage.py
  fec/home/migrations/0113_auto_20210316_1226.py
  fec/home/models.py
  fec/home/templates/blocks/contact-info.html
  fec/home/templates/blocks/custom_table.html
  fec/home/templates/blocks/example-image.html
  fec/home/templates/blocks/example-paragraph.html
  fec/home/templates/blocks/related-media.html
  fec/home/templates/blocks/reporting-example-cards.html
  fec/home/templates/blocks/section.html
  fec/home/templates/home/about_landing_page.html
  fec/home/templates/home/alert_for_emergency_use_only.html
  fec/home/templates/home/calendar.html
  fec/home/templates/home/candidate-and-committee-services/guides.html
  fec/home/templates/home/candidate-and-committee-services/services_landing_page.html
  fec/home/templates/home/collection_page.html
  fec/home/templates/home/commission_meetings.html
  fec/home/templates/home/commissioner_page.html
  fec/home/templates/home/commissioners.html
  fec/home/templates/home/contact-form.html
  fec/home/templates/home/contact_page.html
  fec/home/templates/home/custom_page.html
  fec/home/templates/home/document_feed_page.html
  fec/home/templates/home/document_page.html
  fec/home/templates/home/example_page.html
  fec/home/templates/home/feed_base.html
  fec/home/templates/home/full_width_page.html
  fec/home/templates/home/home_page.html
  fec/home/templates/home/home_page_banner_announcement.html
  fec/home/templates/home/latest_updates.html
  fec/home/templates/home/legal/legal_resources_landing.html
  fec/home/templates/home/meeting_page.html
  fec/home/templates/home/oig_landing_page.html
  fec/home/templates/home/press_landing_page.html
  fec/home/templates/home/reports_landing_page.html
  fec/home/templates/home/resource_page.html
  fec/home/templates/home/updates/digest_page.html
  fec/home/templates/home/updates/press_release_page.html
  fec/home/templates/home/updates/record_page.html
  fec/home/templates/home/updates/tips_for_treasurers.html
  fec/home/templates/partials/audit-search.html
  fec/home/templates/partials/commissioner.html
  fec/home/templates/partials/current-commissioners.html
  package-lock.json
  package.json
  requirements.txt
Labels: Please review, Work: Front-end

#4535 Up-grade under-score
  package-lock.json
  package.json
Labels: Please review, Security: high, Work: Front-end

#4556 Close resourceblock section divs, patch draftail
  fec/fec/static/scss/_fonts.scss
  fec/home/templates/blocks/section.html
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#4555 4173 - Set font faces to swap
  fec/fec/static/scss/_fonts.scss
Labels: Please review, Work: Front-end

#4534 Feature/4177 image element sizes
  fec/fec/static/scss/components/_site-header.scss
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/usa-banner.html
  fec/home/templates/partials/commissioner.html
  fec/home/templates/partials/current-commissioners.html
Labels: Please review, Work: Front-end

#4559 4280 - Update default year
  fec/data/constants.py
Labels: Before release, Please review

#4573 [MERGE WITH GITFLOW - HOTFIX] Downgrade underscore to 1.9.2
  package-lock.json
  package.json
Labels: HOTFIX, High priority, Please review, Work: Front-end

#4578 [MERGE WITH GITFLOW- HOTFIX] Underscore upgrade and template syntax change
  fec/fec/static/js/modules/column-helpers.js
  fec/fec/static/js/modules/election-map.js
  fec/fec/static/js/modules/maps.js
  package-lock.json
  package.json
Labels: HOTFIX, High priority
