Repository fecgov/fec-cms, pull requests merged in 2021-02, with the labels that each got.

#4356 Feature/4355 remove size of contributions
  fec/data/templates/raising-bythenumbers.jinja
  fec/data/templates/spending-bythenumbers.jinja
Labels: Work: Front-end

#4358 Add leadership PACs to about this candidate section of candidate profile pages
  fec/data/templates/partials/candidate/about-candidate.jinja
  fec/data/tests/test_candidate.py
  fec/data/views.py
  fec/fec/static/scss/components/_glossary.scss
Labels: Please review

#4369 Add sponsor link in committee profile
  fec/data/templates/partials/committee/about-committee.jinja
  fec/data/views.py
Labels: Before release, Please review

#4395 [MERGE WITH GIT FLOW] [HOTFIX] Add 2021 and 2022 option to datatables
  fec/data/constants.py
Labels: HOTFIX, Please review

#4359 Feature/3573 feature flag cleanup
  fec/fec/settings/base.py
Labels: Please review, Work: Front-end

#4353 Feature/4351 debts section
  fec/data/constants.py
  fec/data/templates/partials/browse-data/loans-debts.jinja
  fec/data/templates/partials/debts-filter.jinja
  fec/data/tests/test_datatables.py
  fec/data/urls.py
  fec/data/views_datatables.py
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/modules/filters/range-filter.js
  fec/fec/static/js/pages/datatable-debts.js
  fec/fec/static/js/templates/debts.hbs
Labels: Please review, Work: Front-end

#4389 3887 Add trailing slashes to header nav
  fec/fec/templates/partials/navigation/nav-about.html
  fec/fec/templates/partials/navigation/nav-data.html
  fec/fec/templates/partials/navigation/nav-help.html
  fec/fec/templates/partials/navigation/nav-legal.html
  fec/fec/templates/partials/navigation/navigation.html
Labels: Please review, Work: Front-end

#4394 Feature/3620 remove classic url
  fec/fec/settings/base.py
  fec/home/templates/home/commission_meetings.html
  fec/home/templatetags/filters.py
Labels: Please review, Work: Front-end

#4421 [HOT FIX - DON'T MERGE!] Updating chart offices to default to S
  fec/data/views.py
  fec/home/templates/home/home_page.html
  fec/home/templates/partials/oig-most-recent.html
  fec/home/templatetags/top_entities.py
Labels: HOTFIX, Please review, Work: Front-end
