Repository fecgov/fec-cms, pull requests merged in 2021-06, with the labels that each got.

#4635 4622 - Upgrade Django
  requirements.txt
Labels: Please review, Security: high, Work: Front-end

#4655 Activate state election cards on election profile pages
  fec/data/templates/partials/elections/election-profile-cards.jinja
  fec/fec/static/scss/components/_cards.scss
Labels: Please review

#4658 Fix disclaimer text
  fec/data/templates/macros/disclaimer.jinja
  fec/data/urls.py
Labels: Before release, Please review

#4680 Fix link on All Commissioners page
  fec/home/templates/home/commissioners.html
Labels: Before release, Please review

#4653 Create PAC and party datatable
  fec/data/constants.py
  fec/data/templates/partials/browse-data/committees.jinja
  fec/data/templates/partials/pac-party-filter.jinja
  fec/data/urls.py
  fec/data/views_datatables.py
  fec/fec/settings/base.py
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/pages/datatable-pac-party.js
  fec/fec/static/js/templates/pac-party.hbs
Labels: Please review

#4601 feature/4189 cross origin links
  fec/data/templates/layouts/main.jinja
  fec/data/templates/macros/document.jinja
  fec/data/templates/macros/missing-transferred.jinja
  fec/data/templates/macros/missing.jinja
  fec/data/templates/partials/warnings.jinja
  fec/fec/static/js/templates/calendar/details.hbs
  fec/fec/static/js/templates/calendar/events.hbs
  fec/fec/static/js/templates/tables/noData.hbs
  fec/fec/static/scss/components/_documents.scss
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/home/templates/home/alert_for_emergency_use_only.html
  fec/home/templates/home/home_page_banner_announcement.html
  fec/home/templates/home/latest_updates.html
Labels: Before release, Please review, Work: Front-end

#4649 Update IE support messaging
  fec/data/templates/layouts/main.jinja
  fec/data/templates/partials/warnings.jinja
  fec/fec/static/scss/components/_site-header.scss
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
Labels: Before release, Please review

#4685 Sync string values of environment names for GTM
  fec/data/templates/partials/google-tag-manager-noscript.jinja
  fec/data/templates/partials/google-tag-manager-script.jinja
  fec/fec/templates/partials/google-tag-manager-noscript.html
  fec/fec/templates/partials/google-tag-manager-script.html
Labels: Please review, Work: Front-end

#4699 Feature/4698 fix purgecss
  fec/fec/static/js/modules/site-nav.js
  fec/gulpfile.js
  fec/home/templates/purgecss-homepage/banners.html
  fec/home/templates/purgecss-homepage/commissioners.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/hero.html
  fec/home/templates/purgecss-homepage/navs.html
  fec/home/templates/purgecss-homepage/readme.txt
  fec/home/templates/purgecss-homepage/toggled.html
Labels: Please review, Work: Front-end

#4708 4701 - Upgrade Django to 3.1.12
  requirements.txt
Labels: Please review, Work: CMS back-end

#4705 Fix mobile view of browse data sections
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/templates/partials/browse-data/committees.jinja
  fec/data/templates/partials/browse-data/external.jinja
  fec/data/templates/partials/browse-data/filings-reports.jinja
  fec/data/templates/partials/browse-data/loans-debts.jinja
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/browse-data/spending.jinja
Labels: Please review

#4709 Refine display of details panel in PAC and party datatable
  fec/fec/static/js/templates/pac-party.hbs
Labels: Please review

#4715 Feature/3934 new tv ad background
  fec/fec/static/img/new-tv-bkgd-wide.png
  fec/fec/static/scss/components/_responsive-object.scss
Labels: Please review

#4692 PAC & party datatable: default election year applied on load and make time period a single select
  fec/data/templates/macros/filters/years.jinja
  fec/data/templates/partials/pac-party-filter.jinja
  fec/data/views_datatables.py
  fec/fec/static/js/modules/filters/select-filter.js
Labels: Please review

#4702 Feature/4577 update wccf defaults
  fec/fec/static/js/widgets/aggregate-totals-box.js
  fec/fec/static/js/widgets/contributions-by-state-box.js
  fec/fec/static/js/widgets/pres-finance-map-box.js
  fec/fec/static/js/widgets/widget-vars.js
Labels: Please review, Work: Front-end

#4722 [MERGE WITH GIT FLOW] Release/public 20210629
  fec/data/templates/macros/filters/years.jinja
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/templates/partials/browse-data/committees.jinja
  fec/data/templates/partials/browse-data/external.jinja
  fec/data/templates/partials/browse-data/filings-reports.jinja
  fec/data/templates/partials/browse-data/loans-debts.jinja
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/browse-data/spending.jinja
  fec/data/templates/partials/pac-party-filter.jinja
  fec/data/views_datatables.py
  fec/fec/static/img/new-tv-bkgd-wide.png
  fec/fec/static/js/modules/filters/select-filter.js
  fec/fec/static/js/templates/pac-party.hbs
  fec/fec/static/js/widgets/aggregate-totals-box.js
  fec/fec/static/js/widgets/contributions-by-state-box.js
  fec/fec/static/js/widgets/pres-finance-map-box.js
  fec/fec/static/js/widgets/widget-vars.js
  fec/fec/static/scss/components/_responsive-object.scss
  fec/search/management/data/sitemap_pdf.xml
  requirements.txt
Labels: Please review
