Repository fecgov/fec-cms, pull requests merged in 2021-08, with the labels that each got.

#4795 2021 district message for Election search
  fec/data/templates/election-lookup.jinja
  fec/fec/static/js/modules/election-search.js
  fec/fec/static/scss/components/_search-controls.scss
Labels: Before release, Please review

#4785 Show title for copied pages in draft
  fec/home/models.py
Labels: Before release, Please review

#4816 Update Other committees filter label
  fec/data/templates/macros/filters/committee-types.jinja
Labels: Please review

#4598 AF canonical page updates
  fec/data/api_caller.py
  fec/fec/static/scss/components/_entity-header.scss
  fec/fec/static/scss/components/_type-styles.scss
  fec/fec/static/scss/legal-common.scss
  fec/legal/templates/legal-admin_fine.jinja
  fec/legal/templates/partials/legal-search-results-afs.jinja
Labels: Please review

#4812 [MERGE WITH GITFLOW] Release/public 20210810
  fec/data/api_caller.py
  fec/data/templates/committees-single.jinja
  fec/data/templates/election-lookup.jinja
  fec/data/templates/macros/filters/range.jinja
  fec/data/templates/partials/browse-data/committees.jinja
  fec/data/templates/partials/committee/financial-summary.jinja
  fec/data/templates/partials/pac-party-filter.jinja
  fec/data/templatetags/filters.py
  fec/data/views.py
  fec/fec/settings/base.py
  fec/fec/static/js/modules/calendar.js
  fec/fec/static/js/modules/election-search.js
  fec/fec/static/js/templates/calendar/details.hbs
  fec/fec/static/js/templates/calendar/events.hbs
  fec/fec/static/scss/components/_calendar.scss
  fec/fec/static/scss/components/_committee-snapshot.scss
  fec/fec/static/scss/components/_entity-header.scss
  fec/fec/static/scss/components/_search-controls.scss
  fec/fec/static/scss/components/_type-styles.scss
  fec/fec/static/scss/entity.scss
  fec/fec/static/scss/legal-common.scss
  fec/home/models.py
  fec/legal/templates/legal-admin_fine.jinja
  fec/legal/templates/partials/legal-search-results-afs.jinja
Labels: Please review

#4822 Feature/4791 hp pres map link
  fec/fec/static/img/i-complex--data--gray-lightest.svg
  fec/fec/static/scss/elements/_links.scss
  fec/home/templates/purgecss-homepage/full.html
Labels: Please review, Work: Front-end

#4831 Fix admin fines calculator typo
  fec/fec/static/js/modules/calc-admin-fines.js
  fec/fec/static/scss/components/_fec-org-chart.scss
Labels: Please review, Work: Front-end

#4815 Update candidates browse data page
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/static/img/i-graph--primary-contrast.svg
Labels: Please review

#4820 Change 'contributor' to 'source' for Receipts
  fec/data/constants.py
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/receipts-filter.jinja
  fec/fec/static/js/pages/datatable-receipts.js
  fec/fec/static/js/templates/receipts.hbs
Labels: Please review

#4810 Upgrade Wagtail from 2.11.7 -> 2.11.8
  requirements.txt
Labels: Please review, Work: Front-end

#4814 Add two glossary terms
  fec/data/views.py
  fec/fec/static/js/data/terms.json
Labels: Please review, Before release

#4838 remove all references to the FEC_TRANSITION_URL
  fec/fec/settings/base.py
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  manifest_dev.yml
  manifest_feature.yml
  manifest_prod.yml
  manifest_stage.yml
Labels: Please review

#4847 moved i-graph icon to proper place
  fec/fec/static/img/i-graph--primary-contrast.svg
Labels: Before release

#4836 [MERGE WITH GIT FLOW] Release/public 20210824
  fec/data/constants.py
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/receipts-filter.jinja
  fec/data/views.py
  fec/fec/static/img/i-complex--data--gray-lightest.svg
  fec/fec/static/img/i-graph--primary-contrast.svg
  fec/fec/static/js/data/terms.json
  fec/fec/static/js/modules/calc-admin-fines.js
  fec/fec/static/js/pages/datatable-receipts.js
  fec/fec/static/js/templates/receipts.hbs
  fec/fec/static/scss/components/_fec-org-chart.scss
  fec/fec/static/scss/elements/_links.scss
  fec/home/templates/purgecss-homepage/full.html
  requirements.txt
Labels: Please review
