Repository fecgov/fec-cms, pull requests merged in 2021-11, with the labels that each got.

#4939 [MERGE WITH GITFLOW] Release/public-20211102
  fec/data/constants.py
  fec/data/templates/committees-single.jinja
  fec/data/templates/partials/committees-filter.jinja
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/templates/committees.hbs
  fec/fec/static/js/templates/pac-party.hbs
  fec/home/blocks.py
  fec/home/migrations/0119_auto_20211013_1228.py
  fec/home/templates/blocks/af_search.html
  package-lock.json
  package.json
  requirements.txt
Labels: release-branch

#4931 Improved Radform validation
  fec/fec/static/js/pages/contact-form.js
  fec/fec/static/scss/components/_contact-form.scss
  fec/fec/tests/js/contact-form.js
  fec/fec/tests/js/radform-validate.js
  fec/home/templates/home/contact-form.html
  fec/home/views.py
Labels: Please review

#4952 [MERGE WITH GIT FLOW] Hotfix/fix candidates datatable
  fec/fec/static/js/modules/columns.js
Labels: Please review, HOTFIX

#4956 4923-Committees datatable default sort set to registration date
  fec/fec/static/js/pages/datatable-committees.js
Labels: Please review

#4953 4932-Remove "celebrity" from examples for individual contribution search
  fec/data/templates/landing.jinja
Labels: Please review, Work: Front-end

#4948 Don't show individual contributions for inaugural organization type committees
  fec/data/templates/committees-single.jinja
  fec/data/templates/partials/committee/raising.jinja
  fec/data/views.py
Labels: Please review
