Repository fecgov/fec-cms, pull requests merged in 2021-10, with the labels that each got.

#4871 Upgrade npm to latest
  package-lock.json
  package.json
Labels: Please review

#4895 [MERGE WITH GITFLOW] Release/public 20211005
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/partials/pac-party-filter.jinja
  fec/fec/static/js/templates/pac-party.hbs
Labels: release-branch

#4909 Change the label for the qualified and non-contribution PACs
  fec/data/constants.py
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/partials/filters/audit-committee-types.jinja
Labels: Please review, Work: Front-end

#4856 Fix references to first file date/registration date
  fec/data/constants.py
  fec/data/templates/committees-single.jinja
  fec/data/templates/partials/committees-filter.jinja
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/templates/committees.hbs
  fec/fec/static/js/templates/pac-party.hbs
Labels: Please review, Work: Front-end, Work: UX/Design
