Repository fecgov/fec-cms, pull requests merged in 2021-07, with the labels that each got.

#4726 Fix type in data constants
  fec/data/constants.py
Labels: Please review

#4742 Correct glossary terms spacing bug
  fec/fec/static/scss/components/_glossary.scss
Labels: Please review

#4755 Update django to minor v3.1.13
  requirements.txt
Labels: Please review

#4743 4630 Only link to document.file_url if it exists
  fec/home/templates/partials/document.html
Labels: Please review, Work: Front-end

#4746 3979 Calendar tooltip widths
  fec/fec/static/scss/components/_calendar.scss
  fec/fec/static/scss/components/_tooltips.scss
Labels: Please review, Work: Front-end

#4754 Elections page - fix responsive behavior and show currency columns in mobile
  fec/data/templates/elections.jinja
  fec/data/templates/partials/elections/about-this-election-tab.jinja
  fec/data/templates/partials/elections/election-data-and-compliance-tab.jinja
  fec/fec/static/js/modules/table-columns.js
  fec/fec/static/scss/components/_data-container.scss
Labels: Please review

#4713 PAC & party datatable filter panel updates
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/macros/filters/filing-frequency.jinja
  fec/data/templates/partials/pac-party-filter.jinja
  fec/fec/static/scss/components/_data-container.scss
  fec/fec/static/scss/components/_type-styles.scss
Labels: Please review, Work: Front-end

#4775 [BEFORE RELEASE]Add style rule for full width tab nav
  fec/fec/static/scss/components/_data-container.scss
Labels: Please review

#4780 Modify PAC/Party datatable
  fec/data/constants.py
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/macros/filters/filing-frequency.jinja
  fec/data/templates/partials/pac-party-filter.jinja
  fec/fec/static/js/templates/pac-party.hbs
Labels: Before release

#4782 [MERGE WITH GITFLOW] Release/public 20210727
  fec/data/constants.py
  fec/data/templates/elections.jinja
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/macros/filters/filing-frequency.jinja
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/templates/partials/committee/about-committee.jinja
  fec/data/templates/partials/elections/about-this-election-tab.jinja
  fec/data/templates/partials/elections/election-data-and-compliance-tab.jinja
  fec/data/templates/partials/pac-party-filter.jinja
  fec/fec/static/js/modules/table-columns.js
  fec/fec/static/js/templates/committees.hbs
  fec/fec/static/js/templates/pac-party.hbs
  fec/fec/static/scss/components/_calendar.scss
  fec/fec/static/scss/components/_data-container.scss
  fec/fec/static/scss/components/_tooltips.scss
  fec/fec/static/scss/components/_type-styles.scss
  fec/home/templates/partials/document.html
  requirements.txt
Labels: release-branch

#4767 Feature/4718 pac snapshot
  fec/data/templates/committees-single.jinja
  fec/data/templates/partials/committee/financial-summary.jinja
  fec/data/templatetags/filters.py
  fec/data/views.py
  fec/fec/settings/base.py
  fec/fec/static/scss/components/_committee-snapshot.scss
  fec/fec/static/scss/components/_entity-header.scss
  fec/fec/static/scss/entity.scss
Labels: Please review, Work: Front-end

#4783 Update Committees browse data text for pac and party datatable
  fec/data/templates/partials/browse-data/committees.jinja
Labels: Please review

#4786 Add calendar event summary and update styles
  fec/fec/static/js/modules/calendar.js
  fec/fec/static/js/templates/calendar/details.hbs
  fec/fec/static/js/templates/calendar/events.hbs
  fec/fec/static/scss/components/_calendar.scss
Labels: Please review
