Repository fecgov/fec-cms, pull requests merged in 2022-01, with the labels that each got.

#5006 [MERGE WITH GIT FLOW] hotfix/5000 admin fines 2022
  fec/fec/static/js/modules/calc-admin-fines-logic.js
  fec/fec/tests/js/calc-admin-fines.js
Labels: Please review, Work: Front-end, HOTFIX

#5024 Update lxml for security vulnerability
  requirements.txt
Labels: Please review, Work: CMS back-end

#5026 [MERGE WITH GITFLOW] Release/public 20220125
  requirements.txt
Labels: release-branch

#5044 Update glossary to add foreign national terms
  fec/fec/static/js/data/terms.json
Labels: Please review
