Repository fecgov/fec-cms, pull requests merged in 2022-08, with the labels that each got.

#5370 [MERGE WITH GITFLOW] Release/public 20220823
  package-lock.json
Labels: release-branch

#5369 5362 - SNYK Django Reflected File Download
  requirements.txt
Labels: Please review, Work: Front-end

#5395 5387-Upgrade circleci docker images (python 3.8 and PG 12.8), pin flake8
  .circleci/config.yml
  README.md
  requirements.txt
Labels: Please review
