Repository fecgov/fec-cms, pull requests merged in 2022-12, with the labels that each got.

#5443 5215 house and senate overview totals
  fec/data/templates/house-senate-overview.jinja
  fec/data/templates/macros/page-header.jinja
  fec/data/templates/partials/house-senate-overview/election-data.jinja
  fec/data/templates/partials/house-senate-overview/section-contributions-across-time.jinja
  fec/data/templates/partials/house-senate-overview/section-summary.jinja
  fec/data/templates/partials/house-senate-overview/section-totals-for-all-elections.jinja
  fec/data/templates/partials/house-senate-overview/sidebar-nav.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/modules/container-queries.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/modules/party-money-bars.js
  fec/fec/static/js/pages/house-senate-overview-across-time.js
  fec/fec/static/js/pages/house-senate-overview-summary.js
  fec/fec/static/js/widgets/aggregate-totals-box.js
  fec/fec/static/scss/widgets/house-senate-overview.scss
  fec/fec/static/scss/widgets/party-money-bars.scss
Labels: Please review, Work: Front-end

#5508 [MERGE WITH GITFLOW] Release/public 20221213
  fec/data/templates/house-senate-overview.jinja
  fec/data/templates/macros/page-header.jinja
  fec/data/templates/partials/house-senate-overview/election-data.jinja
  fec/data/templates/partials/house-senate-overview/section-contributions-across-time.jinja
  fec/data/templates/partials/house-senate-overview/section-summary.jinja
  fec/data/templates/partials/house-senate-overview/section-totals-for-all-elections.jinja
  fec/data/templates/partials/house-senate-overview/sidebar-nav.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/modules/container-queries.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/modules/party-money-bars.js
  fec/fec/static/js/pages/house-senate-overview-across-time.js
  fec/fec/static/js/pages/house-senate-overview-summary.js
  fec/fec/static/js/widgets/aggregate-totals-box.js
  fec/fec/static/scss/widgets/house-senate-overview.scss
  fec/fec/static/scss/widgets/party-money-bars.scss
Labels: release-branch

#5512 Replace committee_id with q_filer
  fec/fec/static/js/modules/table-columns.js
Labels: Please review

#5514 5481 min/max dates in URLs
  fec/data/views.py
Labels: Please review, Work: Front-end

#5528 [MERGE WITH GITFLOW] Release/public 20221227
  fec/data/views.py
  fec/fec/static/js/modules/table-columns.js
  fec/home/templates/home/commission_meetings.html
  fec/home/templates/home/meeting_page.html
Labels: Please review, release-branch
