Repository fecgov/fec-cms, pull requests merged in 2022-04, with the labels that each got.

#5140 [MERGE WITH GITFLOW] Release/public 20220405
  fec/data/templates/landing.jinja
  requirements.txt
Labels: release-branch

#5145 Fix feedback box errors on full width template
  fec/fec/static/js/pages/reporting-dates-tables.js
  fec/home/templates/home/full_width_page.html
Labels: Please review

#5155 5150-SNYK upgrade moment
  package-lock.json
  package.json
Labels: Please review, Security: high

#5181 upgrade gitpython
  requirements.txt
Labels: Please review
