Repository fecgov/fec-cms, pull requests merged in 2022-03, with the labels that each got.

#5096 [MERGE BEFORE 3/08 RELEASE DEPLOYED] Adds informational snippet block to CMS templates
  fec/home/blocks.py
  fec/home/migrations/0122_auto_20220303_1357.py
  fec/home/models.py
  fec/home/templates/blocks/embed-info-message.html
  fec/home/templates/home/contact_page.html
  fec/home/templates/home/meeting_page.html
Labels: Before release

#5094 Add example paragraph block to ResourcePage termplate
  fec/home/blocks.py
  fec/home/migrations/0122_auto_20220302_2114.py
Labels: Please review

#5098 Shareable accurate datatable links
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/partials/filters/audit-committee-types.jinja
  fec/fec/static/js/modules/tables.js
Labels: Please review

#5136 Swap top /data/ sections
  fec/data/templates/landing.jinja
Labels: Please review, Work: Front-end

#5138 5071 SNYK - Upgrade Pillow (and Wagtail)
  requirements.txt
Labels: Please review, Work: Front-end
