Repository fecgov/fec-cms, pull requests merged in 2022-05, with the labels that each got.

#5166 Contributions across time chart for House/Senate Overview page
  fec/data/templates/house-senate-overview.jinja
  fec/data/templates/macros/cycle-select.jinja
  fec/data/templates/partials/house-senate-overview/election-data.jinja
  fec/data/templates/partials/house-senate-overview/sidebar-nav.jinja
  fec/data/views.py
  fec/fec/static/js/pages/elections-overview.js
  fec/fec/static/scss/widgets/house-senate-overview.scss
Labels: Please review

#5194 Update census accordion language on election search page
  fec/data/templates/election-lookup.jinja
Labels: Please review

#5198 [HOTFIX - MERGE WITH GITFLOW] Update additional info and informational message placement in CMS
  fec/home/templates/home/meeting_page.html
Labels: HOTFIX

#5139 Feature/4352 rad form error events
  fec/fec/static/js/modules/analytics.js
  fec/fec/static/js/pages/contact-form.js
Labels: Please review, Work: Front-end

#5196 All elections totals table
  fec/data/templates/partials/house-senate-overview/election-data.jinja
  fec/data/templates/partials/house-senate-overview/sidebar-nav.jinja
  fec/fec/static/js/pages/elections-overview.js
Labels: Please review

#5221 Update hybrid pac descriptions on committee filters
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/partials/filters/audit-committee-types.jinja
Labels: Please review

#5206 Add links to H/S overviews on Election search page
  fec/data/templates/election-lookup.jinja
  fec/fec/static/scss/layout/_layout.scss
Labels: Please review

#5234 Add methodology feature flag for house & senate overview pages
  fec/data/templates/partials/house-senate-overview/election-data.jinja
  fec/fec/settings/base.py
Labels: Before release

#5228 'Candidate state or territory' label for filings data table
  fec/data/templates/macros/filters/states.jinja
  fec/data/templates/partials/filings-filter.jinja
Labels: Please review

#5237 Update disclaimer text for all totals elections datatable
  fec/data/templates/partials/house-senate-overview/election-data.jinja
Labels: Please review, Before release

#5241 Remove debts from Loans and debts page
  fec/data/templates/browse-data.jinja
  fec/data/templates/partials/browse-data/loans-debts.jinja
  fec/fec/templates/partials/navigation/nav-data.html
Labels: Work: Front-end

#5249 5230 Remove "See a"
  fec/data/templates/raising-bythenumbers.jinja
Labels: Please review, Work: Front-end

#5235 Handle null strings for SA/SB aggregates
  fec/fec/static/js/pages/committee-single.js
Labels: Please review
