Repository fecgov/fec-cms, pull requests merged in 2023-12, with the labels that each got.

#6019 Feature/5992a static election search maps
  fec/fec/static/js/modules/election-lookup.js
  fec/fec/static/js/modules/election-map.js
  fec/fec/static/js/modules/election-search.js
Labels: Please review, Work: Front-end

#6012 5953-upgrade django
  requirements.txt
Labels: Please review

#6011 [MERGE WITH GITFLOW] Release/public 20231205
  fec/data/templates/landing.jinja
  fec/fec/static/img/map-election-search-default.png
  fec/fec/static/js/modules/election-form.js
  fec/fec/static/js/modules/election-lookup.js
  fec/fec/static/js/modules/election-map.js
  fec/fec/static/js/modules/election-search.js
  fec/fec/static/scss/components/_maps.scss
  fec/fec/static/scss/components/_mega-menu.scss
  fec/home/templates/partials/elections-lookup.html
  fec/home/templates/purgecss-homepage/full.html
  requirements.txt
Labels: Please review, release-branch

#6021 Update meeting page templates for 10 am time for 2024
  fec/home/templates/home/commission_meetings.html
  fec/home/templates/home/meeting_page.html
Labels: Please review
