Repository fecgov/fec-cms, pull requests merged in 2023-02, with the labels that each got.

#5591 Allow cycle greater than DEFAULT_TIME_PERIOD to show efiling data
  fec/data/views.py
Labels: Please review

#5601 Sort MUR by case_no
  fec/fec/static/scss/components/_table-styles.scss
  fec/legal/templates/legal-search-results-murs.jinja
  fec/legal/templates/partials/legal-pagination.jinja
  fec/legal/templates/partials/legal-search-results-mur.jinja
  fec/legal/views.py
Labels: Please review

#5594 Replace topojson
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/modules/election-map.js
  fec/fec/static/js/modules/election-utils.js
  fec/fec/static/js/modules/maps.js
  package-lock.json
  package.json
Labels: Please review

#5597 Setup pre-commit git hook
  .flake8
  .pre-commit-config.yaml
  pytest.ini
  requirements.txt
Labels: Please review

#5600 remove natives and fs, use graceful fs instead
  fec/gulpfile.js
  fec/webpack.config.js
  package-lock.json
  package.json
Labels: Please review

#5611 replace nswatch with npm-watch and concurrently
  package-lock.json
  package.json
Labels: Please review

#5612 5607 - Election pages methodology buttons
  fec/data/templates/house-senate-overview.jinja
Labels: Please review, Work: Front-end

#5614 [MERGE WITH GITFLOW] Release/public 20230221
  .flake8
  .pre-commit-config.yaml
  fec/data/templates/house-senate-overview.jinja
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/modules/election-map.js
  fec/fec/static/js/modules/election-utils.js
  fec/fec/static/js/modules/maps.js
  fec/fec/static/scss/components/_table-styles.scss
  fec/gulpfile.js
  fec/legal/templates/legal-search-results-murs.jinja
  fec/legal/templates/partials/legal-pagination.jinja
  fec/legal/templates/partials/legal-search-results-mur.jinja
  fec/legal/views.py
  fec/webpack.config.js
  package-lock.json
  package.json
  pytest.ini
  requirements.txt
Labels: release-branch

#5621 Update terms.json
  fec/fec/static/js/data/terms.json
Labels: Please review

#5628 5622-Add 2023-2024 links
  fec/data/templates/partials/browse-data/bulk-data.jinja
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/templates/partials/browse-data/committees.jinja
  fec/data/templates/partials/browse-data/filings-reports.jinja
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/browse-data/spending.jinja
Labels: Please review
