Repository fecgov/fec-cms, pull requests merged in 2023-09, with the labels that each got.

#5890 upgrade node
  .circleci/config.yml
  package-lock.json
  package.json
Labels: Please review

#5875 [MERGE WITH GITFLOW] Release/public 20230905
  .circleci/config.yml
  fec/data/templates/house-senate-overview.jinja
  fec/data/templates/macros/cycle-select.jinja
  fec/data/templates/partials/browse-data/filings-reports.jinja
  fec/data/templates/partials/house-senate-overview/section-totals-for-all-elections.jinja
  fec/fec/middleware.py
  fec/fec/static/js/modules/download.js
  fec/fec/static/js/pages/house-senate-overview-summary.js
  fec/fec/static/js/pages/house-senate-overview-totals.js
  fec/fec/static/js/widgets/pres-finance-map-box.js
  fec/fec/static/scss/components/_data-container.scss
  fec/search/management/data/sitemap_html.xml
  fec/search/management/data/sitemap_pdf.xml
  package-lock.json
  package.json
  requirements.txt
  tasks.py
Labels: Please review, release-branch

#5885 Document URL field for document list
  fec/home/blocks.py
  fec/home/migrations/0131_auto_20230905_2038.py
  fec/home/templates/blocks/document-list.html
Labels: Please review

#5903 Add new statistical summary table for PACS
  fec/fec/static/js/pages/statistical-summary.js
Labels: Please review

#5906 [MERGE WITH GITFLOW]Release/public 20230918
  fec/fec/static/js/pages/statistical-summary.js
  fec/home/blocks.py
  fec/home/migrations/0131_auto_20230905_2038.py
  fec/home/templates/blocks/document-list.html
  fec/home/templates/home/candidate-and-committee-services/guides.html
Labels: Please review, release-branch

#5908 Unobscure date-filter placeholder text
  fec/fec/static/scss/elements/_forms.scss
Labels: Please review

#5925 Remove code related to scraping and indexing for search.gov i14y drawer
  .gitignore
  fec/fec/settings/base.py
  fec/search/management/commands/index_pages.py
  fec/search/management/commands/scrape_cms_pages.py
  fec/search/management/commands/scrape_transition_pages.py
  fec/search/management/commands/scrape_web_app_pages.py
  fec/search/management/data/transition_pages.json
  fec/search/management/data/web_app_pages.json
  fec/search/management/instructions.md
  fec/search/tests/test_indexing.py
  fec/search/utils/search_indexing.py
Labels: Please review

#5765 4413 - Debts datatable
  fec/data/constants.py
  fec/data/templates/browse-data.jinja
  fec/data/templates/macros/tables.jinja
  fec/data/templates/partials/browse-data/loans-debts.jinja
  fec/data/templates/partials/debts-filter.jinja
  fec/data/tests/test_committee.py
  fec/data/urls.py
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/pages/datatable-debts.js
  fec/fec/static/js/templates/debts.hbs
  fec/fec/templates/partials/navigation/nav-data.html
  tasks.py
Labels: Please review, Work: Front-end

#5933 New lastmod for fecfrm3pposti.pdf and fecfrm4i.pdf
  fec/search/management/data/sitemap_pdf.xml
Labels: Please review

#5931 [MERGE BEFORE 09/28/23 RELEASE] Add link to document page
  fec/home/templates/home/document_page.html
Labels: Please review, Before release
