Repository fecgov/fec-cms, pull requests merged in 2023-04, with the labels that each got.

#5672 Update Congressional Districts shape files
  fec/data/constants.py
  fec/data/templates/election-lookup.jinja
  fec/fec/static/js/data/create_districts_topo.sh
  fec/fec/static/js/data/districts.json
  fec/fec/static/js/data/merge_shape_files.py
  fec/fec/static/js/data/notes.md
Labels: Please review

#5695 [MERGE WITH GIT FLOW] Hotfix/use new codecov uploader
  .circleci/config.yml
  requirements.txt
Labels: Please review

#5700 Update district map cutoff to 2024
  fec/data/constants.py
Labels: Please review, Before release

#5704 [HOTFIX - MERGE WITH GITFLOW] Hotfix/5701 add 2024 pres export links v2
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/views.py
Labels: Please review, Before release, HOTFIX

#5710 Corrects styling of AM to a.m. for open meeting first paragraph
  fec/home/templates/home/meeting_page.html
Labels: Please review

#5705 [MERGE WITH GITFLOW] Release/public 20230425
  fec/data/constants.py
  fec/data/templates/election-lookup.jinja
  fec/fec/static/js/data/create_districts_topo.sh
  fec/fec/static/js/data/districts.json
  fec/fec/static/js/data/merge_shape_files.py
  fec/fec/static/js/data/notes.md
  fec/fec/static/js/widgets/contributions-by-state-box.js
Labels: release-branch
