Repository fecgov/fec-cms, pull requests merged in 2023-11, with the labels that each got.

#5984 5946- upgrade urllib3
  requirements.txt
Labels: Please review

#5988 Feature/5987 homepage barcharts to p
  fec/data/views.py
  fec/fec/static/js/widgets/contributions-by-state-box.js
  fec/home/templates/home/home_page.html
  fec/home/templates/partials/raising-spending.html
  fec/home/templatetags/top_entities.py
Labels: Please review, Before release, Work: Front-end

#5975 Exclude duplicate press releases in /updates
  fec/home/models.py
  fec/home/views.py
  tasks.py
Labels: Please review

#5995 rm feature deploy task
  tasks.py
Labels: Please review

#5983 Fix hidden-rows-bug on Wagtail tableblocks
  fec/fec/static/css/customize-editor.css
  fec/home/blocks.py
Labels: Please review

#5989 Ensure date is aligned right on heading w/ date
  fec/fec/static/scss/components/_headings.scss
Labels: Please review

#6010 6002 - Main nav layout
  fec/fec/static/scss/components/_mega-menu.scss
Labels: Please review, Work: Front-end
