Repository fecgov/fec-cms, pull requests merged in 2023-01, with the labels that each got.

#5534 5509-upgrade gitpython
  requirements.txt
Labels: Please review

#5537 [MERGE WITH GIT FLOW] 5507 admin fines calculator 2023
  fec/fec/static/js/modules/calc-admin-fines-logic.js
  fec/fec/tests/js/calc-admin-fines.js
Labels: Please review, Work: Front-end, HOTFIX

#5535 [MERGE WITH GITFLOW] Release/public 20230110
  requirements.txt
Labels: Please review, release-branch

#5550 5488- Upgrade setuptools
  requirements.txt
Labels: Please review

#5574 Add Type to footer button
  fec/data/templates/layouts/main.jinja
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
Labels: Please review

#5582 Feature/5572 replace http with https
  README.md
  fec/data/templates/partials/browse-data/external.jinja
  fec/data/templates/partials/browse-data/filings-reports.jinja
  fec/data/views.py
  fec/fec/static/js/data/notes.md
  fec/fec/static/js/templates/electionZipWarning.hbs
  fec/fec/templates/partials/env-banner.html
  fec/home/templates/home/commissioner_page.html
  fec/home/templates/purgecss-homepage/banners.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
  fec/legal/templates/legal-advisory-opinion.jinja
  fec/search/management/instructions.md
Labels: Please review

#5566 5554-upgrade node 18.13.0 LTS
  .circleci/config.yml
  fec/fec/static/scss/components/_calendar.scss
  fec/fec/static/scss/components/_search-controls.scss
  fec/fec/static/scss/vendor/bourbon/_bourbon-deprecated-upcoming.scss
  fec/fec/static/scss/vendor/bourbon/addons/_triangle.scss
  fec/fec/static/scss/vendor/bourbon/functions/_px-to-em.scss
  fec/fec/static/scss/vendor/bourbon/functions/_px-to-rem.scss
  fec/fec/static/scss/vendor/bourbon/functions/_strip-units.scss
  fec/fec/static/scss/vendor/neat/grid/_private.scss
  fec/gulpfile.js
  package-lock.json
  package.json
Labels: Please review

#5585 Feature/4988 upgrade circleci docker image pg13
  .circleci/config.yml
  README.md
Labels: Please review
