Repository fecgov/fec-cms, pull requests merged in 2023-10, with the labels that each got.

#5954 5953 - Homepage, update election and voting info url
  fec/home/templates/home/home_page.html
  fec/home/templates/purgecss-homepage/full.html
Labels: Please review, Work: Front-end

#5938 Update disbursement search language
  fec/data/templates/partials/browse-data/spending.jinja
Labels: Work: Content

#5957 Fix server error on some reports
  fec/home/templates/home/document_page.html
Labels: Please review, Before release

#5937 fix calendar export
  fec/data/templates/layouts/main.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/modules/calendar-helpers.js
  fec/fec/static/js/pages/calendar-page.js
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
Labels: Please review, Before release

#5962 Debts - fixing deployment
  fec/fec/settings/base.py
  tasks.py
Labels: Please review, High priority

#5960 [MERGE WITH GITFLOW] Release/public 20231024
  fec/data/constants.py
  fec/data/templates/layouts/main.jinja
  fec/data/templates/macros/tables.jinja
  fec/data/templates/partials/browse-data/loans-debts.jinja
  fec/data/templates/partials/browse-data/spending.jinja
  fec/data/templates/partials/debts-filter.jinja
  fec/data/tests/test_committee.py
  fec/fec/settings/base.py
  fec/fec/static/js/modules/calendar-helpers.js
  fec/fec/static/js/pages/calendar-page.js
  fec/fec/static/js/templates/debts.hbs
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/home/templates/home/document_page.html
  fec/home/templates/home/home_page.html
  fec/home/templates/purgecss-homepage/full.html
  fec/search/management/data/sitemap_pdf.xml
  requirements.txt
  tasks.py
Labels: release-branch

#5980 [HOTFIX - MERGE WITH GITHUB] 5977 Map Tiles Redirects
  fec/fec/settings/base.py
  fec/fec/static/js/modules/election-map.js
  fec/fec/static/js/modules/maps.js
  fec/fec/static/scss/components/_maps.scss
  fec/home/templates/purgecss-homepage/full.html
  package-lock.json
  package.json
Labels: Please review, Work: Front-end, High priority, HOTFIX

#5961 5904 About Menu: Intro to Campaign Finance and Elections
  fec/fec/static/scss/components/_icon-headings.scss
  fec/fec/static/scss/components/_mega-menu.scss
  fec/fec/templates/partials/navigation/nav-about.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
Labels: Please review, Work: Front-end
