Repository fecgov/fec-cms, pull requests merged in 2023-07, with the labels that each got.

#5796 [MERGE WITH GITFLOW] Release/public 20230717
  fec/fec/static/css/customize-editor.css
  fec/fec/static/js/pages/election-reporting-dates-tables.js
  fec/fec/static/scss/components/_table-styles.scss
  fec/home/blocks.py
  fec/home/migrations/0129_reportingdatestable.py
  fec/home/migrations/0130_alter_reportingdatestable_reporting_dates_table.py
  fec/home/models.py
  fec/home/templates/blocks/reporting-dates-table-block.html
  fec/home/templates/home/reporting_dates_table.html
  fec/home/templatetags/filters.py
  package-lock.json
  package.json
Labels: release-branch

#5719 Add new allocated federal/nonfederal disbursements datatable
  fec/data/constants.py
  fec/data/templates/macros/filters/text.jinja
  fec/data/templates/macros/tables.jinja
  fec/data/templates/partials/allocated-federal-nonfederal-disbursements-filter.jinja
  fec/data/templates/partials/browse-data/spending.jinja
  fec/data/templates/partials/committee-totals-pac-party.jinja
  fec/data/templates/partials/independent-expenditures-filter.jinja
  fec/data/tests/test_datatables.py
  fec/data/urls.py
  fec/data/views_datatables.py
  fec/fec/settings/base.py
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/pages/datatable-allocated-federal-nonfederal-disbursements.js
  fec/fec/static/js/templates/allocated-federal-nonfederal-disbursements.hbs
  fec/fec/static/js/templates/debts.hbs
  fec/fec/static/js/templates/disbursements.hbs
  fec/fec/static/js/templates/loans.hbs
  fec/fec/static/js/templates/receipts.hbs
  fec/fec/tests/js/helpers.js
  tasks.py
Labels: Please review, Work: Front-end

#5813 [MERGE WITH GITFLOW] Release/public 20230725
  fec/data/constants.py
  fec/data/templates/macros/filters/text.jinja
  fec/data/templates/macros/tables.jinja
  fec/data/templates/partials/allocated-federal-nonfederal-disbursements-filter.jinja
  fec/data/templates/partials/browse-data/spending.jinja
  fec/data/templates/partials/committee-totals-pac-party.jinja
  fec/data/templates/partials/independent-expenditures-filter.jinja
  fec/data/tests/test_datatables.py
  fec/data/urls.py
  fec/data/views_datatables.py
  fec/fec/settings/base.py
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/pages/datatable-allocated-federal-nonfederal-disbursements.js
  fec/fec/static/js/templates/allocated-federal-nonfederal-disbursements.hbs
  fec/fec/static/js/templates/debts.hbs
  fec/fec/static/js/templates/disbursements.hbs
  fec/fec/static/js/templates/loans.hbs
  fec/fec/static/js/templates/receipts.hbs
  fec/fec/tests/js/helpers.js
  tasks.py
Labels: release-branch

#5814 upgrade django
  requirements.txt
Labels: Please review
