Repository fecgov/fec-cms, pull requests merged in 2024-02, with the labels that each got.

#6100 Upgrade gitpython
  requirements.txt
Labels: Please review

#6099 [MERGE WITH GITFLOW] Release/public 20240206
  bin/run.sh
  fec/fec/settings/base.py
  fec/fec/templates/snippets/index_custom_button.html
  fec/home/migrations/0003_auto_20150819_0342.py
  fec/home/migrations/0132_auto_20231130_1233.py
  fec/home/models.py
  fec/home/wagtail_hooks.py
  requirements.txt
Labels: release-branch

#6035 6027 - Remove Grey from Election Search Maps
  fec/fec/static/js/modules/election-map.js
Labels: Please review, Work: Front-end

#6051 5964 Update Social Icons
  fec/data/templates/layouts/main.jinja
  fec/fec/static/img/i-x-twitter--primary.png
  fec/fec/static/img/i-x-twitter--primary.svg
  fec/fec/static/scss/_icon-variables.scss
  fec/fec/static/scss/components/_footer.scss
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/home/templates/home/commissioner_page.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
Labels: Please review, Work: Front-end

#6105 migrate deploy to run in circleci
  .circleci/config.yml
Labels: Please review

#6121 [MERGE WITH GITFLOW] Release/public 20240220
  .circleci/config.yml
  fec/data/templates/layouts/main.jinja
  fec/fec/static/img/i-x-twitter--primary.png
  fec/fec/static/img/i-x-twitter--primary.svg
  fec/fec/static/js/modules/election-map.js
  fec/fec/static/scss/_icon-variables.scss
  fec/fec/static/scss/components/_footer.scss
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/home/templates/home/commissioner_page.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
  requirements.txt
Labels: Please review, release-branch

#6124 Update the term compensation to json ticket #6120
  fec/fec/static/js/data/terms.json
Labels: Please review

#6119 upgrade jinja2
  requirements.txt
Labels: Please review

#6130 Feature/5713 upgrade django v4.2
  fec/fec/settings/base.py
  fec/home/migrations/0133_alter_recordpagetag_tag.py
  fec/home/templatetags/home_page.py
  requirements.txt
Labels: Please review, Pipeline: Ready

#6117 6080 - Update Election Search
  fec/data/templates/election-lookup.jinja
  fec/fec/static/js/modules/election-search.js
  fec/fec/static/scss/components/_messages.scss
  tasks.py
Labels: Please review, Work: Front-end
