Repository fecgov/fec-cms, pull requests merged in 2024-09, with the labels that each got.

#6456 [MERGE WITH GITFLOW] Release/public 20240903
  bin/run.sh
  fec/data/api_caller.py
  fec/data/tests/test_legal_search.py
  fec/fec/static/js/legal.js
  fec/fec/static/js/legal/Filters.cjs
  fec/fec/static/js/modules/keyword-modal.js
  fec/home/migrations/0136_alter_embedsnippet_banner_icon_and_more.py
  fec/home/templates/partials/legal-keyword-modal.html
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/macros/legal.jinja
  fec/legal/templates/partials/legal-keyword-modal.jinja
  fec/legal/views.py
  package-lock.json
  package.json
  requirements.txt
  tasks.py
Labels: release-branch

#6460 Limit 10 candidates for contribution by size and state
  fec/fec/static/js/modules/tables.js
  fec/fec/static/js/templates/comparison.hbs
  fec/fec/static/scss/components/_dropdowns.scss
  fec/fec/tests/js/tables.js
Labels: Please review

#6415 6414 Dates & Time Elements
  fec/data/templates/partials/candidate/other-spending-tab.jinja
  fec/data/templates/partials/candidate/raising.jinja
  fec/data/templates/partials/candidate/spending.jinja
  fec/data/templates/partials/committee/raising.jinja
  fec/data/templates/partials/committee/spending.jinja
  fec/data/templatetags/filters.py
Labels: Please review, Work: Front-end

#6349 6329 - Remove Internet Explorer
  fec/data/templates/layouts/main.jinja
  fec/data/templates/layouts/widgets.jinja
  fec/data/templates/partials/meta-tags.jinja
  fec/data/templates/partials/warnings.jinja
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/polyfills.js
  fec/fec/static/scss/components/_site-header.scss
  fec/fec/static/scss/widgets/party-money-bars.scss
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/meta-tags.html
  fec/home/templates/home/calendar.html
  fec/home/templates/home/home_page.html
  fec/home/templates/purgecss-homepage/banners.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#6472 Outdated browsers banner - fix the homepage
  fec/fec/templates/home_base.html
Labels: Please review, Before release, Work: Front-end

#6471 [MERGE WITH GITFLOW]Release/public 20240917
  fec/data/templates/layouts/main.jinja
  fec/data/templates/layouts/widgets.jinja
  fec/data/templates/partials/candidate/other-spending-tab.jinja
  fec/data/templates/partials/candidate/raising.jinja
  fec/data/templates/partials/candidate/spending.jinja
  fec/data/templates/partials/committee/raising.jinja
  fec/data/templates/partials/committee/spending.jinja
  fec/data/templates/partials/meta-tags.jinja
  fec/data/templates/partials/warnings.jinja
  fec/data/templatetags/filters.py
  fec/fec/static/img/beta-fec-fb.png
  fec/fec/static/img/beta-fec-tw.png
  fec/fec/static/img/us_flag_small.png
  fec/fec/static/js/modules/data-map.js
  fec/fec/static/js/modules/tables.js
  fec/fec/static/js/polyfills.js
  fec/fec/static/js/templates/comparison.hbs
  fec/fec/static/scss/components/_dropdowns.scss
  fec/fec/static/scss/components/_hero.scss
  fec/fec/static/scss/components/_maps.scss
  fec/fec/static/scss/components/_site-header.scss
  fec/fec/static/scss/widgets/party-money-bars.scss
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/meta-tags.html
  fec/fec/tests/js/tables.js
  fec/gulpfile.js
  fec/home/templates/home/calendar.html
  fec/home/templates/home/home_page.html
  fec/home/templates/purgecss-homepage/banners.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
  package-lock.json
  package.json
Labels: release-branch
