Repository fecgov/fec-cms, pull requests merged in 2024-10, with the labels that each got.

#6475 Add download headshot button to commissioner pages
  fec/home/migrations/0137_commissionerpage_picture_download.py
  fec/home/models.py
  fec/home/templates/home/commissioner_page.html
Labels: Please review

#6496 Add a11y modal dialog to global.js
  fec/fec/static/js/data-init.js
  fec/fec/static/js/global.js
  fec/fec/static/js/init.js
  fec/home/templates/home/full_width_page.html
Labels: Please review

#6522 MUR Final disposition filter
  fec/data/constants.py
  fec/fec/static/scss/components/_dropdowns.scss
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/legal-search-results-murs.jinja
  fec/legal/templates/partials/legal-pagination.jinja
  fec/legal/views.py
Labels: Please review

#6526 6504 MURs Final Disposition Tooltip
  fec/data/templates/macros/filters/checkbox.jinja
  fec/legal/templates/legal-search-results-murs.jinja
Labels: Please review, Work: Front-end

#6524 [MERGE WITH GITFLOW] Release/public 20241029
  fec/data/constants.py
  fec/fec/static/scss/components/_dropdowns.scss
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/legal-search-results-murs.jinja
  fec/legal/templates/partials/legal-pagination.jinja
  fec/legal/views.py
Labels: release-branch
