Repository fecgov/fec-cms, pull requests merged in 2024-03, with the labels that each got.

#6139 remove feature branch
  tasks.py
Labels: Please review, Before release

#6131 [MERGE WITH GITFLOW] Release/public 20240305
  fec/data/templates/election-lookup.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/data/terms.json
  fec/fec/static/js/modules/election-search.js
  fec/fec/static/scss/components/_messages.scss
  fec/home/migrations/0133_alter_recordpagetag_tag.py
  fec/home/templatetags/home_page.py
  fec/search/management/data/sitemap_pdf.xml
  requirements.txt
Labels: Please review, release-branch

#6134 upgrade python v3.10
  .circleci/config.yml
  README.md
  requirements.txt
  runtime.txt
Labels: Please review

#6135 Update sitemap_pdf.xml
  fec/search/management/data/sitemap_pdf.xml
Labels: Please review

#6154 [MERGE WITH GITFLOW]Release/public 20240318
  .circleci/config.yml
  README.md
  fec/search/management/data/sitemap_pdf.xml
  requirements.txt
  runtime.txt
Labels: Please review, release-branch

#6165 Office template anchors and rich-text
  fec/home/templates/home/office_page.html
Labels: Work: Front-end

#6153 Update terms.json for Tech Modernization
  fec/fec/static/js/data/terms.json
Labels: Work: Content

#6171 update statutes example search
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/legal-statutes-landing.jinja
  fec/legal/templates/macros/legal.jinja
Labels: Please review
