Repository fecgov/fec-cms, pull requests merged in 2024-06, with the labels that each got.

#6313 [MERGE WITH GITFLOW] Release/public 20240604
  .circleci/config.yml
  fec/data/constants.py
  fec/data/templates/datatable.jinja
  fec/data/templates/layouts/main.jinja
  fec/data/templates/macros/filters/dropdown-json.jinja
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/browse-data/spending.jinja
  fec/data/templates/partials/disbursements-filter.jinja
  fec/data/templates/partials/meta-tags.jinja
  fec/data/templates/partials/national-party-account-disbursements-filter.jinja
  fec/data/templates/partials/national-party-account-receipts-filter.jinja
  fec/data/templates/partials/receipts-filter.jinja
  fec/data/tests/test_datatables.py
  fec/data/urls.py
  fec/data/views_datatables.py
  fec/fec/settings/base.py
  fec/fec/static/js/modules/column-helpers.js
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/modules/filters/select-filter.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/pages/datatable-national-party-account-disbursements.js
  fec/fec/static/js/pages/datatable-national-party-account-receipts.js
  fec/fec/static/js/templates/allocated-federal-nonfederal-disbursements.hbs
  fec/fec/static/js/templates/disbursements.hbs
  fec/fec/static/js/templates/national-party-account-disbursements.hbs
  fec/fec/static/js/templates/national-party-account-receipts.hbs
  fec/fec/static/scss/components/_footer.scss
  fec/fec/static/scss/components/_hero.scss
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/footer-navigation.html
  fec/fec/templates/partials/meta-tags.html
  fec/home/templates/home/oig_landing_page.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
  manifest_prod.yml
  package-lock.json
  package.json
Labels: Please review

#6328 Add missing 1979-1980 bulk data
  fec/data/templates/partials/browse-data/bulk-data.jinja
Labels: Please review

#6322 6206 upgrade dompurify
  package-lock.json
  package.json
Labels: Please review

#6332 [MERGE WITH GITFLOW] Release/public 20240618
  fec/data/api_caller.py
  fec/data/templates/partials/browse-data/bulk-data.jinja
  fec/data/tests/test_legal_search.py
  fec/fec/static/js/data-init.js
  fec/fec/static/scss/components/_datatable-panel.scss
  fec/fec/static/scss/components/_results-info.scss
  fec/fec/static/scss/components/_tags.scss
  fec/fec/static/scss/mixins/_utilities.scss
  fec/fec/templates/partials/navigation/nav-legal.html
  fec/home/templates/home/legal/legal_resources_landing.html
  fec/home/templates/purgecss-homepage/full.html
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/legal-search-results-adrs.jinja
  fec/legal/templates/legal-search-results-afs.jinja
  fec/legal/templates/legal-search-results-murs.jinja
  fec/legal/templates/legal-search-results.jinja
  fec/legal/templates/macros/legal.jinja
  fec/legal/templates/partials/legal-pagination.jinja
  fec/legal/templates/partials/legal-search-results-adrs.jinja
  fec/legal/templates/partials/legal-search-results-afs.jinja
  fec/legal/templates/partials/legal-search-results-mur.jinja
  fec/legal/views.py
  package-lock.json
  package.json
Labels: release-branch

#6276 Error handling for about/careers (USAJobs API)
  fec/home/templatetags/open_jobs.py
  fec/home/tests/test_usajobs.py
Labels: Please review

#6336 6292, 6293 ZIP Codes in details panels
  fec/fec/static/js/templates/allocated-federal-nonfederal-disbursements.hbs
  fec/fec/static/js/templates/debts.hbs
  fec/fec/static/js/templates/disbursements.hbs
  fec/fec/static/js/templates/loans.hbs
  fec/fec/static/js/templates/national-party-account-disbursements.hbs
  fec/fec/static/js/templates/national-party-account-receipts.hbs
  fec/fec/static/js/templates/party-coordinated-expenditures.hbs
  fec/fec/static/js/templates/receipts.hbs
  fec/fec/static/scss/components/_datatable-panel.scss
Labels: Please review, Work: Front-end

#6348 6347 - Remove links and permissions for polyfill.io
  fec/fec/middleware.py
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
Labels: Please review, Work: Front-end, High priority, Security: high
