Repository fecgov/fec-cms, pull requests merged in 2024-04, with the labels that each got.

#6173 [MERGE WITH GITFLOW] Release/public 20240402
  fec/data/templates/partials/house-senate-overview/section-contributions-across-time.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/data/terms.json
  fec/fec/static/js/pages/house-senate-overview-across-time.js
  fec/home/templates/home/meeting_page.html
  fec/home/templates/home/office_page.html
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/legal-statutes-landing.jinja
  fec/legal/templates/macros/legal.jinja
Labels: Please review, release-branch

#6156 upgrade to pg v15
  .circleci/config.yml
  README.md
Labels: Please review

#6174 Remove banners from sitemap and search index
  fec/home/models.py
Labels: Please review

#6194 [MERGE WITH GITFLOW] Release/public 20240417
  .circleci/config.yml
  README.md
  fec/data/constants.py
  fec/data/templates/macros/filters/dropdown-json.jinja
  fec/data/templates/partials/disbursements-filter.jinja
  fec/data/templates/partials/receipts-filter.jinja
  fec/fec/static/js/modules/filters/filter-set.js
  fec/fec/static/js/modules/filters/filter-tags.js
  fec/fec/static/js/modules/filters/select-filter.js
  fec/home/models.py
Labels: release-branch

#6202 Add separate internal API public key
  fec/data/templates/layouts/main.jinja
  fec/data/templates/layouts/widgets.jinja
  fec/fec/context.py
  fec/fec/settings/base.py
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/tests/test_api_key.py
Labels: Please review, Before release

#6214 Expand keyword search on /updates to include html content
  fec/home/views.py
Labels: Please review, Before release

#6216 Update ADR feature
  fec/data/api_caller.py
  fec/home/blocks.py
  fec/home/templates/blocks/adr_search.html
  fec/legal/templates/legal-adr.jinja
  fec/legal/templates/legal-search-results-adrs.jinja
  fec/legal/templates/macros/legal.jinja
  fec/legal/templates/partials/legal-search-results-adrs.jinja
Labels: Before release

#6224 Remove eqs.fec.gov references across the website
  fec/home/templates/blocks/af_search.html
  fec/home/templates/blocks/mur_search.html
  fec/legal/templates/legal-search-results-adrs.jinja
  fec/legal/templates/legal-search-results-afs.jinja
  fec/legal/templates/legal-search-results-murs.jinja
  fec/legal/templates/legal-search-results.jinja
Labels: Please review, Before release
