Repository fecgov/fec-cms, pull requests merged in 2024-07, with the labels that each got.

#6344 [MERGE WITH GITFLOW] Release/public 20240702
  fec/fec/middleware.py
  fec/fec/static/js/templates/allocated-federal-nonfederal-disbursements.hbs
  fec/fec/static/js/templates/debts.hbs
  fec/fec/static/js/templates/disbursements.hbs
  fec/fec/static/js/templates/loans.hbs
  fec/fec/static/js/templates/national-party-account-disbursements.hbs
  fec/fec/static/js/templates/national-party-account-receipts.hbs
  fec/fec/static/js/templates/party-coordinated-expenditures.hbs
  fec/fec/static/js/templates/receipts.hbs
  fec/fec/static/scss/components/_datatable-panel.scss
  fec/fec/templates/500-status.html
  fec/fec/templates/base.html
  fec/home/templatetags/open_jobs.py
  fec/home/tests/test_usajobs.py
Labels: release-branch

#6355 Allow CustomPage as child of AboutLandingPage
  fec/home/models.py
Labels: Please review

#6345 Add missing migration for CMS
  fec/home/migrations/0135_alter_resourcepage_sections.py
Labels: Please review

#6353 Add legal search to global search autosuggest
  fec/fec/static/js/modules/typeahead.js
  fec/fec/static/scss/components/_search-bar.scss
  fec/legal/templates/legal-search-results.jinja
Labels: Please review, Before release

#6364 [MERGE WITH GITFLOW] Release/public 20240717
  fec/fec/static/js/modules/typeahead.js
  fec/fec/static/scss/components/_search-bar.scss
  fec/home/migrations/0135_alter_resourcepage_sections.py
  fec/home/models.py
  fec/legal/templates/legal-search-results.jinja
  requirements.txt
Labels: Please review, release-branch

#6382 [HOTFIX - MERGE WITH GITFLOW ] 6378 Quotes in Search
  fec/fec/static/js/modules/helpers.js
  fec/fec/tests/js/helpers.js
  package-lock.json
  package.json
Labels: Work: Front-end, High priority, HOTFIX

#6383 [HOTFIX - MERGE WITH GITFLOW] 6378 Quotes in Search 2
  fec/fec/static/js/modules/typeahead.js
Labels: Please review, Work: Front-end, High priority, HOTFIX

#6359 6305 National Party Accounts Types Filters Labels
  fec/data/constants.py
  fec/data/templates/macros/filters/dropdown-json.jinja
  fec/data/templates/partials/national-party-account-disbursements-filter.jinja
  fec/data/templates/partials/national-party-account-receipts-filter.jinja
Labels: Please review, Before release, Work: Front-end

#6391 Feature/6390 webpack 5 fixes
  .cspell/custom-dictionary-workspace.txt
  fec/data/constants.py
  fec/data/templates/browse-data.jinja
  fec/data/templates/candidates-single.jinja
  fec/data/templates/committees-single.jinja
  fec/data/templates/datatable.jinja
  fec/data/templates/election-lookup.jinja
  fec/data/templates/elections.jinja
  fec/data/templates/house-senate-overview.jinja
  fec/data/templates/landing.jinja
  fec/data/templates/layouts/main.jinja
  fec/data/templates/macros/filters/dropdown-json.jinja
  fec/data/templates/partials/national-party-account-disbursements-filter.jinja
  fec/data/templates/partials/national-party-account-receipts-filter.jinja
  fec/data/templates/partials/widgets/contributions-by-state.jinja
  fec/data/templates/raising-bythenumbers.jinja
  fec/data/templates/spending-bythenumbers.jinja
  fec/data/templates/widgets/pres-finance-map.jinja
  fec/fec/static/js/draftail/Anchor.js
  fec/fec/static/js/draftail/App.js
  fec/fec/static/js/draftail/Glossary.js
  fec/fec/static/js/draftail/SansSerif.js
  fec/fec/static/js/init.js
  fec/fec/static/js/modules/calc-admin-fines-modal.js
  fec/fec/static/js/modules/statistical-summary-archive.js
  fec/fec/static/js/pages/data-landing.js
  fec/fec/static/js/pages/statistical-summary.js
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/tests/js/draftail/anchor.js
  fec/fec/tests/js/draftail/glossary.js
  fec/fec/tests/js/draftail/sansserif.js
  fec/home/templates/home/calendar.html
  fec/home/templates/home/home_page.html
  fec/home/templates/home/legal/legal_resources_landing.html
  fec/home/templates/home/reporting_dates_table.html
  fec/legal/templates/layouts/legal-doc-landing.jinja
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/webpack.config.cjs
  package-lock.json
  tasks.py
Labels: Please review, Work: Front-end, High priority

#6366 6258-upgrade requests
  requirements.txt
Labels: Please review
