Repository fecgov/fec-cms, pull requests merged in 2024-05, with the labels that each got.

#6225 Info or alert banner above intro on ResourcePage
  fec/home/migrations/0134_embedsnippet_banner_icon_alter_resourcepage_intro.py
  fec/home/models.py
  fec/home/templates/blocks/embed-info-message.html
Labels: Please review

#6190 Review by 5/13: Feature/6167 regulation search using ecfr api
  fec/data/ecfr_caller.py
  fec/data/legal_test_data.py
  fec/data/tests/test_legal_search.py
  fec/fec/static/scss/components/_data-container.scss
  fec/fec/static/scss/components/_legal-search.scss
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/legal-search-results-regulations.jinja
  fec/legal/templates/legal-search-results.jinja
  fec/legal/templates/macros/legal.jinja
  fec/legal/templates/partials/legal-regulations-pagination.jinja
  fec/legal/templates/partials/legal-search-results-regulation.jinja
  fec/legal/views.py
Labels: Please review, Before release

#6243 ADR Canonical - Alternate row striping by disposition
  fec/legal/templates/legal-adr.jinja
Labels: Please review

#6230 Faster keyword search for updates and html search for legacy meetings
  fec/home/views.py
Labels: Please review

#6254 6208-upgrade gunicorn
  requirements.txt
Labels: Please review

#6265 [MERGE WITH GITFLOW] Release/public 20240521
  fec/data/ecfr_caller.py
  fec/data/legal_test_data.py
  fec/data/tests/test_legal_search.py
  fec/fec/static/scss/components/_data-container.scss
  fec/fec/static/scss/components/_legal-search.scss
  fec/home/migrations/0134_embedsnippet_banner_icon_alter_resourcepage_intro.py
  fec/home/models.py
  fec/home/templates/blocks/embed-info-message.html
  fec/home/views.py
  fec/legal/templates/layouts/legal-doc-search-results.jinja
  fec/legal/templates/legal-adr.jinja
  fec/legal/templates/legal-search-results-regulations.jinja
  fec/legal/templates/legal-search-results.jinja
  fec/legal/templates/macros/legal.jinja
  fec/legal/templates/partials/legal-regulations-pagination.jinja
  fec/legal/templates/partials/legal-search-results-regulation.jinja
  fec/legal/views.py
  fec/search/management/data/sitemap_pdf.xml
  requirements.txt
Labels: release-branch

#6274 6132- add temporary es5 pin
  package-lock.json
  package.json
Labels: Please review

#6281 OIG - move background color to oig-logo instead of its parent
  fec/fec/static/scss/components/_hero.scss
  fec/home/templates/home/oig_landing_page.html
Labels: Please review, Work: Front-end

#6279 PR: 6098 - footer work
  fec/data/templates/layouts/main.jinja
  fec/fec/static/scss/components/_footer.scss
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
  fec/fec/templates/partials/footer-navigation.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
  package-lock.json
  package.json
Labels: Please review, Work: Front-end

#6311 increase memory for prod to 1.5
  manifest_prod.yml
Labels: Please review

#6273 PR: 6179, 6180 national party account
  fec/data/constants.py
  fec/data/templates/datatable.jinja
  fec/data/templates/layouts/main.jinja
  fec/data/templates/macros/filters/dropdown-json.jinja
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/browse-data/spending.jinja
  fec/data/templates/partials/disbursements-filter.jinja
  fec/data/templates/partials/meta-tags.jinja
  fec/data/templates/partials/national-party-account-disbursements-filter.jinja
  fec/data/templates/partials/national-party-account-receipts-filter.jinja
  fec/data/templates/partials/receipts-filter.jinja
  fec/data/tests/test_datatables.py
  fec/data/urls.py
  fec/data/views_datatables.py
  fec/fec/settings/base.py
  fec/fec/static/js/modules/column-helpers.js
  fec/fec/static/js/modules/columns.js
  fec/fec/static/js/modules/filters/select-filter.js
  fec/fec/static/js/modules/helpers.js
  fec/fec/static/js/pages/datatable-national-party-account-disbursements.js
  fec/fec/static/js/pages/datatable-national-party-account-receipts.js
  fec/fec/static/js/templates/allocated-federal-nonfederal-disbursements.hbs
  fec/fec/static/js/templates/national-party-account-disbursements.hbs
  fec/fec/static/js/templates/national-party-account-receipts.hbs
  fec/fec/templates/partials/meta-tags.html
Labels: Please review, Before release, Work: Front-end
