Repository fecgov/fec-cms, pull requests merged in 2024-12, with the labels that each got.

#6562 [MERGE WITH GITFLOW] Release/public 20241126
  fec/data/templates/macros/filters/checkbox.jinja
  fec/data/templates/macros/filters/committee-types.jinja
  fec/data/templates/macros/filters/contributor-states.jinja
  fec/data/templates/macros/filters/districts.jinja
  fec/data/templates/macros/filters/states.jinja
  fec/data/templates/macros/filters/years.jinja
  fec/data/templates/partials/filters/audit-committee-types.jinja
  fec/fec/settings/base.py
  fec/fec/static/js/modules/dropdowns.js
  fec/fec/static/js/modules/tables.js
  fec/fec/static/js/templates/comparison.hbs
  fec/fec/static/js/templates/feedback.hbs
  fec/fec/static/scss/components/_dropdowns.scss
  fec/fec/static/scss/components/_feedback.scss
  fec/fec/tests/js/tables.js
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/toggled.html
  package-lock.json
  package.json
  requirements.txt
Labels: release-branch

#6569 5225 - Show HREF on Print-outs
  fec/fec/static/scss/components/_datatables.scss
  fec/fec/static/scss/components/_site-header.scss
  fec/fec/static/scss/components/_table-styles.scss
  fec/fec/static/scss/elements/_elements.scss
Labels: Please review, Work: Front-end

#6565 6564 - Fix canonical rel links
  fec/data/templates/layouts/main.jinja
  fec/data/templates/partials/meta-tags.jinja
  fec/fec/templates/base.html
  fec/fec/templates/home_base.html
Labels: Please review, Work: Front-end

#6607 [HOTFIX - MERGE WITH GITFLOW] Upgrade Django to the latest patch version to resolve the critical SQ…
  requirements.txt
Labels: Please review, HOTFIX
