Repository fecgov/fec-cms, pull requests merged in 2024-08, with the labels that each got.

#6373 Add load testing using locust
  README.md
  locust_helpers/helpers.py
  locust_helpers/urls.py
  locustfile.py
  requirements-dev.txt
  requirements.txt
Labels: Please review

#6406 6182, 6183 National Party Accounts Data on Single Pages
  fec/data/templates/committees-single.jinja
  fec/data/templates/partials/committee/raising.jinja
  fec/data/templates/partials/committee/spending.jinja
  fec/data/tests/test_committee.py
  fec/data/views.py
  fec/fec/settings/base.py
  fec/fec/static/js/pages/committee-single.js
  fec/fec/static/scss/elements/_elements.scss
Labels: Please review, Work: Front-end, High priority

#6407 6316 National Party Datatables Cycles Selector Limits
  fec/data/templates/macros/filters/years.jinja
  fec/data/templates/partials/national-party-account-disbursements-filter.jinja
  fec/data/templates/partials/national-party-account-receipts-filter.jinja
Labels: Please review, Work: Front-end

#6403 Document highlights for MUR/ADR on global legal search results
  fec/legal/templates/legal-search-results.jinja
  fec/legal/templates/partials/legal-search-results-adrs.jinja
  fec/legal/templates/partials/legal-search-results-mur.jinja
Labels: Please review

#6420 Bump wagtail to 5.2.6 to fix vulnerability
  requirements.txt
Labels: Please review

#6412 [MERGE WITH GITFLOW] Release/public 20240813
  README.md
  fec/data/templates/committees-single.jinja
  fec/data/templates/macros/filters/years.jinja
  fec/data/templates/partials/committee/raising.jinja
  fec/data/templates/partials/committee/spending.jinja
  fec/data/templates/partials/national-party-account-disbursements-filter.jinja
  fec/data/templates/partials/national-party-account-receipts-filter.jinja
  fec/data/tests/test_committee.py
  fec/data/views.py
  fec/fec/settings/base.py
  fec/fec/static/js/pages/committee-single.js
  fec/fec/static/scss/components/_sidebar.scss
  fec/fec/static/scss/elements/_elements.scss
  fec/legal/templates/legal-search-results.jinja
  fec/legal/templates/partials/legal-search-results-adrs.jinja
  fec/legal/templates/partials/legal-search-results-mur.jinja
  locust_helpers/helpers.py
  locust_helpers/urls.py
  locustfile.py
  requirements-dev.txt
  requirements.txt
Labels: release-branch

#6430 [HOTFIX - MERGE WITH GITFLOW] 6429 NPA Single Page Updates
  fec/data/templates/partials/committee/raising.jinja
  fec/data/templates/partials/committee/spending.jinja
Labels: Work: Front-end, High priority, HOTFIX

#6426 Upgrade urllib3v2.2.2
  requirements.txt
Labels: Please review

#6425 upgrade django v4.2.15
  requirements.txt
Labels: Please review

#6427 Remove unused node pkgs, es6-weak-map and es5-ext
  package-lock.json
  package.json
Labels: Please review

#6424 Commit missing migration 0136 to develop branch
  fec/home/migrations/0136_alter_embedsnippet_banner_icon_and_more.py
Labels: Please review
