Repository fecgov/fec-cms, pull requests merged in 2025-02, with the labels that each got.

#6657 upgrade cf cli
  .circleci/config.yml
  package-lock.json
  package.json
Labels: Please review

#6668 6666 Fix icons for cards with alternating backgrounds
  fec/fec/static/scss/components/_cards.scss
Labels: Please review, Work: Front-end

#6669 6656 - Add Bluesky Option to Commissioners' Pages
  fec/fec/static/icons/input/bluesky-circle.svg
  fec/fec/static/icons/output/bluesky-circle.svg
  fec/fec/static/img/i-bluesky--primary.png
  fec/fec/static/img/i-bluesky--primary.svg
  fec/fec/static/scss/_icon-variables.scss
  fec/home/migrations/0139_commissionerpage_commissioner_bluesky_and_more.py
  fec/home/models.py
  fec/home/templates/home/commissioner_page.html
Labels: Please review, Work: Front-end

#6671 [MERGE WITH GITFLOW] Release/public 20250211
  .circleci/config.yml
  fec/data/templates/partials/browse-data/bulk-data.jinja
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/templates/partials/browse-data/committees.jinja
  fec/data/templates/partials/browse-data/filings-reports.jinja
  fec/data/templates/partials/browse-data/raising.jinja
  fec/data/templates/partials/browse-data/spending.jinja
  fec/fec/static/icons/input/bluesky-circle.svg
  fec/fec/static/icons/output/bluesky-circle.svg
  fec/fec/static/img/i-bluesky--primary.png
  fec/fec/static/img/i-bluesky--primary.svg
  fec/fec/static/scss/_icon-variables.scss
  fec/fec/static/scss/components/_cards.scss
  fec/fec/wagtail_hooks.py
  fec/home/migrations/0139_commissionerpage_commissioner_bluesky_and_more.py
  fec/home/models.py
  fec/home/templates/home/commissioner_page.html
  fec/home/wagtail_hooks.py
  package-lock.json
  package.json
  requirements.txt
Labels: release-branch

#6672 Update Django to a minor patch version to fix the snyk vulnerability
  requirements.txt
Labels: Please review

#6678 Update jinja to a minor patch version to fix snyk vulnerability
  requirements.txt
Labels: Please review

#6644 6616 - AO search - swap entity_name with commenter and representative
  fec/legal/templates/legal-search-results-advisory_opinions.jinja
  fec/legal/templates/partials/legal-pagination.jinja
  fec/legal/views.py
Labels: Please review, Before release, Work: Front-end

#6681 Add 2025-2026 links for bulk datasets
  fec/data/templates/partials/browse-data/candidates.jinja
Labels: Please review, Before release

#6674 6122 - Admin Fines Calc Visual Polish
  fec/fec/static/js/modules/calc-admin-fines-logic.js
  fec/fec/static/scss/components/_calc-admin-fines.scss
Labels: Please review, Before release, Work: Front-end

#6693 Update year and office constants
  fec/data/constants.py
  fec/data/views.py
  fec/home/templates/home/home_page.html
  fec/home/templatetags/top_entities.py
Labels: Please review, Before release

#6683 [MERGE WITH GITFLOW] Release/public 20250225
  fec/data/constants.py
  fec/data/templates/partials/browse-data/candidates.jinja
  fec/data/views.py
  fec/fec/static/js/modules/calc-admin-fines-logic.js
  fec/fec/static/scss/components/_calc-admin-fines.scss
  fec/fec/static/scss/components/_dropdowns.scss
  fec/home/templates/home/home_page.html
  fec/home/templatetags/top_entities.py
  fec/legal/templates/legal-search-results-advisory_opinions.jinja
  fec/legal/templates/partials/legal-pagination.jinja
  fec/legal/views.py
  requirements.txt
Labels: Please review, release-branch
