Repository fecgov/fec-cms, pull requests merged in 2025-07, with the labels that each got.

#6810 6800-upgrade requests
  requirements.txt
Labels: Please review

#6753 Move from jQuery .focus, .blur
  fec/fec/static/js/modules/calendar-tooltip.js
  fec/fec/static/js/modules/calendar.js
  fec/fec/static/js/modules/download.js
  fec/fec/static/js/modules/dropdowns.js
  fec/fec/static/js/modules/filters/date-filter.js
  fec/fec/static/js/modules/filters/filter-panel.js
  fec/fec/static/js/modules/filters/filter-typeahead.js
  fec/fec/static/js/modules/filters/text-filter.js
  fec/fec/static/js/modules/search.js
  fec/fec/static/js/modules/skip-nav.js
  fec/fec/static/js/modules/tables.js
  fec/fec/static/js/pages/contact-form.js
  fec/fec/static/js/pages/reporting-dates-tables.js
Labels: Please review, Work: Front-end

#6831 6829 Update Default Election Years
  fec/data/constants.py
Labels: Please review, Work: Front-end, release-branch
