Repository fecgov/fec-cms, pull requests merged in 2025-03, with the labels that each got.

#6699 [HOTFIX - MERGE WITH GITFLOW] Update footer
  fec/fec/templates/partials/footer-navigation.html
  fec/home/templates/purgecss-homepage/full.html
  fec/home/templates/purgecss-homepage/navs.html
Labels: HOTFIX

#6690 5353 - Add Donations Tables for Inaugural Committees
  fec/data/templates/committees-single.jinja
  fec/data/templates/partials/committee/raising.jinja
  fec/data/templates/partials/committee/spending.jinja
  fec/fec/static/js/modules/tables.js
  fec/fec/static/js/pages/committee-single.js
Labels: Please review, Work: Front-end

#6695 5667 Wagtail Page Descriptions
  fec/home/models.py
Labels: Please review, Work: Front-end

#6697 Change Citations filters labels for AO & MURs
  fec/legal/templates/legal-search-results-advisory_opinions.jinja
  fec/legal/templates/legal-search-results-murs.jinja
Labels: Please review, Work: Front-end

#6713 [MERGE WITH GIT FLOW]Hotfx to make CustomPage a parent-type for PressReleasePage
  fec/home/models.py
Labels: HOTFIX

#6720 [HOTFIX - MERGE WITH GITFLOW] Hotfix/calendar event time style fix
  fec/fec/static/scss/components/_calendar.scss
Labels: Work: Front-end, High priority, HOTFIX

#6722 6706-upgrade django
  requirements.txt
Labels: Please review, Before release

#6702 2808 - Don't remove side padding for smallest $lg widths
  fec/fec/static/scss/layout/_layout.scss
Labels: Please review, Before release, Work: Front-end

#6706 Rewrite AO legal citations to point to the eCFR
  fec/legal/templates/legal-advisory-opinion.jinja
Labels: Bug, Please review, Before release

#6705 Add q_exclude to statutes
  fec/legal/views.py
Labels: Please review, Before release

#6715 4258 - Auto-size block-table table columns
  fec/fec/static/scss/components/_articles.scss
Labels: Please review, Before release, Work: Front-end

#6736 Remove the label
  fec/fec/static/img/map-election-search-default.png
Labels: Work: Front-end
